### ISSUE TITLE
Documentation Proguard Settings

### ISSUE THREAD

**Issue by phil-brown** [segmentio/analytics-android#109]
I had to add this block to my *proguard* file in order to compile the project. I don't remember seeing this in the documentation - would be nice if it were.

````
# Segment
-dontwarn com.bugsnag.**
-dontwarn com.leanplum.**
-dontwarn com.squareup.**
````

Are there other proguard rules I am missing?

**Comment by kurtisnelson** [comment]
I had to add:
```
-dontwarn com.mixpanel.android.**
-dontwarn ly.count.android.**
-dontwarn com.bugsnag.android.**
-dontwarn com.amplitude.api.**
-dontwarn com.actionbarsherlock.app.**
-dontwarn com.google.android.gms.location.**
```
It probably all varies based on what integrations are being used.

**Comment by f2prateek** [comment]
Added to our public docs, closing.
