### ISSUE TITLE
Register for Push Notifications

### ISSUE THREAD

**Issue by tonytaing** [segmentio/analytics-android#152]
The iOS library supports an abstracted method for registering devices for push notification https://segment.com/docs/libraries/ios/#how-do-i-use-push-notifications-

However, the Android library doesn't support this. The doc https://segment.com/docs/libraries/android/#how-can-i-use-an-integration-specific-feature-e-g-mixpanel-s-push-notifications- recommends calling the 3rd party instead.

Would it be possible to get this implemented to have feature parity with the iOS library?

**Comment by f2prateek** [comment]
Closing this as there no plans currently to implement this, but we might revisit in the future.
