### ISSUE TITLE
Any way to reset analytics on logout.

### ISSUE THREAD

**Issue by johnryan** [segmentio/analytics-android#155]
Is there any way to reset the analytics when a user logs out? the iOS library has a reset method, but I can't find any documentation of this on android.

**Comment by f2prateek** [comment]
You can use [`analytics.logout()`](https://oss.sonatype.org/service/local/repositories/releases/archive/com/segment/analytics/android/core/2.5.1/core-2.5.1-javadoc.jar/!/index.html).
