### ISSUE TITLE
more than one library with package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by mbmc** [segmentio/analytics-android#156]
Today, I'm facing this error while compiling my project.
Seems that excluding module solves the problem:
```
dependencies {
    // ...
    compile 'com.google.android.gms:play-services:6.5.87'
    compile ('com.segment.analytics.android:all:+@aar') {
        exclude module: 'play-services-wearable'
        exclude module: 'play-services-base'
        transitive = true
    }
}
```

**Comment by f2prateek** [comment]
Can you try the later version?

```
dependencies {
// ...
compile 'com.segment.analytics.android:all:2.5.1@aar'
}
```

**Comment by mbmc** [comment]
can't find com.segment.analytics.Analytics

**Comment by f2prateek** [comment]
Oh sorry needs to be, 

```
dependencies {
// ...
compile ('com.segment.analytics.android:all:2.5.1@aar') {
        transitive = true
}
}
```

**Comment by mbmc** [comment]
It gives the "more than one library with package name 'com.google.android.gms'" error, unless I do that
```
    compile ('com.segment.analytics.android:all:2.5.1@aar') {
        exclude module: 'play-services-base'
        transitive = true
    }
```
but I see that in the logs:
```
E/Segment ( 9976): Did not initialize integration AppsFlyer as it was disabled.
E/Segment ( 9976): Did not initialize integration Localytics as it was disabled.
E/Segment ( 9976): Did not initialize integration Crittercism as it was disabled.
E/Segment ( 9976): Did not initialize integration Leanplum as it was disabled.
```

**Comment by f2prateek** [comment]
That's the right message - you don't have these integrations enabled for your project, correct? This will only be logged when you have debugging enabled.

**Comment by f2prateek** [comment]
Do you have any other dependencies for Play Services? Could you share the output of `./gradlew dependencies` for your project?

**Comment by mbmc** [comment]
About the messages, right, it's not enabled.
I do have a dependency on Google Play (see first post).

**Comment by f2prateek** [comment]
If you (or any of your other dependencies) have a dependency on Play Services, you'll have to exclude the one provided by us.
