### ISSUE TITLE
Queue not dispatching automatically

### ISSUE THREAD

**Issue by drspaceboo** [segmentio/analytics-android#157]
After updating to 2.5.0 or 2.5.1 the queue doesn't dispatch automatically when it reaches it's time or size limits. We had to roll back to 2.4.6 to get this working again.

**Comment by f2prateek** [comment]
Can you send me the logs?

**Comment by drspaceboo** [comment]
There is no erorring or anything, just the usual logging of things getting added to the queue. Not sure if it will be useful for diagnosis. I can still send it through if you would like.

**Comment by f2prateek** [comment]
Would be helpful since I would need more information to debug this issue. Also the code with which you're tracking an event would be helpful to reproduce.

**Comment by drspaceboo** [comment]
I tried making a sample project to recreate the issue but couldn't. Also we are moving away from using your ALL package in favour of the CORE package which we aren't seeing the issue for. Unfortunately that means I don't have any more time allocated to resolve this issue. My apologies about that. I didn't record the logs at the time. Feel free to close this issue since it can't be recreated.

**Comment by f2prateek** [comment]
No worries, do let me know if this occurs in 2.5.1

**Comment by drspaceboo** [comment]
Just had a chat to my colleague, he tells me we were having the issue with 2.5.0 this morning. After updating the test to that version I can recreate it every time here is a download of the simple project, just put in your write key to test https://www.dropbox.com/s/9rttlk7aj7u91rv/SegmentIOTest.zip

He is also experiencing the issue with 2.5.1, but I can't recreate that locally. So we have dropped back to 2.4.6 of the core SDK for now.

**Comment by f2prateek** [comment]
Thanks, I'll try it out. 2.5.0 had the issue since the url for our server was incorrect, but it should have been fixed in 2.5.1.
