### ISSUE TITLE
How to find the anonymous ID for alias (String, String)

### ISSUE THREAD

**Issue by somghosh** [segmentio/analytics-android#160]
I can see that segment.io in Android automatically gives an anonymous ID for someone I haven't identified and sends track() events with this ID. After this person logs in and I have got his Database id (from my server response) in the Android phone, I want to alias and set his old anonymous id to newly acquired database id. How can I do that?

For this I need to find out what segment.io is using as the alias at that point of time? is there a way of doing it? Thanks

**Comment by f2prateek** [comment]
You should use `analytics.alias(null, newId)` and then call `analytics.identify(newId)`. Does that work?

**Comment by somghosh** [comment]
Thanks a lot @f2prateek  - I am testing. But it seems that Segment caches my old user id somehow even if I log out? Is there a way to remove segment.io cache . Otherwise I have to use a totally different phone to test this.

**Comment by f2prateek** [comment]
You can uninstall and reinstall the app, or clear data from the system settings.

Within your own app, if you have a logout functionality, you can call `analytics.logout()`, which will clear the cache.

**Comment by somghosh** [comment]
Thanks , when I do analytics.alias(null, newId), it fails at the following  : void clearCharges();

01-19 15:32:36.021  10844-13168/com.gmspartners.earthmiles.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.gmspartners.earthmiles.debug, PID: 10844
    java.lang.NullPointerException
            at com.mixpanel.android.mpmetrics.MixpanelAPI.alias(MixpanelAPI.java:269)
            at com.segment.analytics.MixpanelIntegration.alias(MixpanelIntegration.java:77)
            at com.segment.analytics.AliasPayload.run(AliasPayload.java:44)
            at com.segment.analytics.IntegrationManager.run(IntegrationManager.java:298)
            at com.segment.analytics.IntegrationManager.performOperation(IntegrationManager.java:283)
            at com.segment.analytics.IntegrationManager$IntegrationHandler.handleMessage(IntegrationManager.java:455)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5586)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by f2prateek** [comment]
Oh I think I know what the issue is, let me try out the fix and I'll get back to you.

**Comment by f2prateek** [comment]
Just realized I did this fix over the weekend, could you try the latest snapshot release?

```
 repositories { maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' } }
   compile('com.segment.analytics.android:all:2.5.3-SNAPSHOT@aar') {
    transitive = true
   }
}
```

**Comment by wjwarren** [comment]
Hi @f2prateek,

Just wanted to chime in on this issue since I am working on using `alias()` as well. I don't see the `Analytics.alias(null, newId)` call failing, so it looks like the latest snapshot works.

I do, however, think that the aliasing isn't actually working. I don't see any data that should have been aliased appear under the same 'user profile' in MixPanel People.

When I call `Analytics.alias(null, newId)`, I see a LogCat output with `AliasPayload{userId=oldId, previousId=oldId}`. Looking at the source [code for the Analytics class](https://github.com/segmentio/analytics-android/blob/master/core/src/main/java/com/segment/analytics/Analytics.java#L422), I see that the 'newId' in the 'alias' method isn't used, other than it is checked for not being empty. This is mentioned in [an older issue](https://github.com/segmentio/analytics-android/pull/119) as well.

I am using the Segment core library. I tried adding a compile dependency on the MixPanel SDK, but that seems to make no difference.

Cheers,

Wijnand

**Comment by f2prateek** [comment]
@wjwarren Yeah I see the problem now.

Alias works in tandem with identify, so you should actually use:

```java
analytics.identify(newId);
analytics.identify(previousId, newId);
```

This doesn't help @somghosh, who needs the previousId (the anonymous id that we generated). Let me see what we can do to fix it.

**Comment by somghosh** [comment]
Is there no function to get the anonymous Id?

**Comment by wjwarren** [comment]
@f2prateek Thank you for your reply. I do, however, see no `identify` method that takes 2 Strings as an argument.

**Comment by f2prateek** [comment]
@wjwarren sorry, the second one was supposed to be alias.

**Comment by wjwarren** [comment]
@f2prateek I tried that before, but then the output in LogCat becomes `AliasPayload{userId=newId, previousId=newId}`. I read through the comments on #119, which said that the order of calling `alias` and 'identify' doesn't matter. I am afraid that now I am stuck at the same problem as @somghosh.

**Comment by f2prateek** [comment]
I'll add a way to get the anonymous ID and changing the alias signature to make it easier to understand. This is what it will look like.

```java
String previousId = analytics.identify(newId);
analytics.alias(previousId);
```

**Comment by f2prateek** [comment]
The snapshot will be ready to try out in a couple of hours.

**Comment by wjwarren** [comment]
@f2prateek Awesome, thanks a lot! :smile: Please let me know when the shapshot is out.

**Comment by wjwarren** [comment]
@f2prateek How do I get the snapshot? Is it available from Maven Central or should I clone the repo?

**Comment by f2prateek** [comment]
It's not on Maven Central yet, but in the snapshots repo instead. Just add it to you repositories section and update the version number. I'll make a release on Monday that will have this change.

```
repositories { maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' } }
  compile('com.segment.analytics.android:all:2.5.3-SNAPSHOT@aar') {
    transitive = true
  }
}
```

**Comment by somghosh** [comment]
Hi @f2prateek 

I see that currently, alias() accepts previousId and options as arguments, shouldn't it be newId and options? How do I specify the newId otherwise?

thanks


	   */
	  public void alias(String previousId, Options options) {
		if (isNullOrEmpty(previousId)) {
		  throw new IllegalArgumentException("previousId must not be null or empty.");
		}
		if (options == null) {
		  options = defaultOptions;
		}

		BasePayload payload = new AliasPayload(analyticsContext, options, previousId);
		submit(payload);
	  }

**Comment by f2prateek** [comment]
@somghosh You would first call identify with the newId, and then call alias with the old id.

```java
String previousId = analytics.identify(newId);
analytics.alias(previousId);
```

**Comment by f2prateek** [comment]
The alias call will automatically use the currentUserId as the newUserId internally.

**Comment by somghosh** [comment]
Understood, thanks @f2prateek . I tried this out, however, seems like things are not working in Mixpanel still. Please find screenshots attached - in the debugger and in the mixpanel People screen - as you would see only events after identify/alias is associated with the user - while aliasing would also make the Signup Page screen event (ActivitySignup_) appear in Mixpanel before Registration as well (other screen events are appearing as events in Mixpanel as you can see on the top)


![3](https://cloud.githubusercontent.com/assets/5731118/6018311/9defc984-ab8d-11e4-8426-7b027e8fed6c.png)

![2](https://cloud.githubusercontent.com/assets/5731118/6018315/a186555e-ab8d-11e4-8f2a-7ec0d96215bc.png)

My code is as below and for the events in the screen, I am passing doAlias = true.

    public void analyticsIdentify(boolean doAlias){
        Realm realm = Realm.getInstance(this, ACCOUNT_DATA_DB);
        AccountData userData = realm.where(AccountData.class).findFirst();


        if (userData!= null){
            Log.d("XXX", "Analytics Identify called, ID = " + userData.getId() +" First Name = " + userData.getFirstName());
            String previousId;
            
            previousId = getAnalytics().identify(
                    String.valueOf(userData.getId()),
                    new Traits()
                            .putFirstName(userData.getFirstName())
                            .putLastName(userData.getLastName())
                            .putBirthday(userData.getAge())
                            .putEmail(userData.getEmail())
                            .putValue("Location", userData.getLocationCity())
                            .putBirthday(userData.getAge())
                            .putValue("IsFacebook", userData.isFacebook())
                            .putName(userData.getFirstName() + " " + userData.getLastName()),
                    null);                                      // no extra options

            if (doAlias){
                getAnalytics().alias(previousId);                   //alias previousId to maintain continuity of events on same user
            }
        } else{
           if (DEBUG){
                Toast.makeText(this, "Found no user for doing Segment Identify, identifying as anonymous", Toast.LENGTH_SHORT).show();
            }

        }

    }

**Comment by wjwarren** [comment]
@f2prateek @somghosh Same happens for me. I see the `alias` and `identify` calls, but the data that should be aliased, isn't showing up under the same user in Mixpanel.

**Comment by f2prateek** [comment]
I'll look into it. Is this with the bundled integration, or are you using the server side integration?

**Comment by wjwarren** [comment]
I'm using server side.

**Comment by somghosh** [comment]
I'm using the bundled integration

**Comment by f2prateek** [comment]
@somghosh can you send me the logs?

**Comment by f2prateek** [comment]
@wjwarren what user does it show under?

**Comment by wjwarren** [comment]
In Mixpanel it shows as an anonymous user with the same `anonymousId` as the known user.

**Comment by somghosh** [comment]
Same for me actually. I dont see it in People in Mixpanel, but see an event
in Trends with id = anon id

**Comment by somghosh** [comment]
@f2prateek let us know when you have a solution for this. Many thanks in advance

**Comment by somghosh** [comment]
Many thanks @f2prateek . Could you please let me know if anything has changed in the aliasing syntax/function now ? tx

**Comment by f2prateek** [comment]
@somghosh This is how the new version will work. We'll automatically do the right things in the background.
```
 analytics.track("user did something");
 analytics.alias(newId, options);
 analytics.identify(newId);
```

**Comment by zafrani** [comment]
This isn't working. Mix panel still has everything under an anonymous id after identifying. I'm on com.segment.analytics.android:analytics-core:3.4.0

**Comment by jodhavishalsingh** [comment]
You can simply use this code:

            analytics.ready(function(){
                var user = analytics.user();
                var anonymousId  = user.anonymousId();
            });

**Comment by kushalkadaba** [comment]
I am also facing this issue, where Alias and Identify payloads are getting created and uploaded (according to the logcat) but, on mixpanel the events under anonymous id aren't connected to the userId. Any pointers on how to debug this issue?

**Comment by f2prateek** [comment]
1. Upgrade to the latest version.
2. Enable logging if still not working.
3. Send logs to friends@segment.com if it still not working.

**Comment by kushalkadaba** [comment]
@f2prateek A little more background on this issue. The first time an anonymous id is aliased with a user id, the alias works fine. However, when 
1. The user logs out 
2. Opens the app again (there is a new anonymous id created)
3. All events are recorded under the new anonymous id.
4. User logs back in
5. App UserId is aliased with the new anonymous id in Step 2 and doesn't work.
