### ISSUE TITLE
Translate Mixpanel Special Properties

### ISSUE THREAD

**Issue by f2prateek** [segmentio/analytics-android#165]
https://mixpanel.com/docs/properties-or-segments/special-or-reserved-properties

**Comment by adrienkohlbecker** [comment]
Hi @f2prateek ! I'm the guy who submitted this ticket.
Do you have an estimate on when this will be implemented ?
I'm willing to help with a PR if you give me some pointers

**Comment by f2prateek** [comment]
@adrienkohlbecker This might need a bit of structuring, but if you want to tackle it, thanks for volunteering a fix! Basically you'll need to fill this [`JSONObject`](https://github.com/segmentio/analytics-android/blob/master/analytics-integrations/mixpanel/src/main/java/com/segment/analytics/internal/integrations/MixpanelIntegration.java#L103) with the right keys.

So, for instance, email would be copied over as:
```
props.put("$email", payload.email());
```

You'll notice that currently only properties are passed to the `event` method, you'll have to change that to pass in `BasePayload`, which holds extra properties such as email, name, etc.

I'll get to this next week if you can't, but we won't be making an official release until v3 unfortunately. The snapshots will be released regularly, so you're welcome to try that out in the meantime!

**Comment by adrienkohlbecker** [comment]
Looking at the code, shouldn't it be done in the identify call for the People properties? ($email, $first_name...)
Here: https://github.com/segmentio/analytics-android/blob/master/analytics-integrations/mixpanel/src/main/java/com/segment/analytics/internal/integrations/MixpanelIntegration.java#L69

While v3 is unreleased, is there a way to do this inside my app, such as calling identify on the Mixpanel integration with different parameters than the other integrations ?

**Comment by msimr** [comment]
@adrienkohlbecker Yep and this is how it's done in iOS.
https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Mixpanel/SEGMixpanelIntegration.m#L49

**Comment by f2prateek** [comment]
Closed by https://github.com/segmentio/analytics-android/commit/d83426a8cd689cfa7865d28f9505e0c9fc3bbf9e

**Comment by adrienkohlbecker** [comment]
This is great! I'm releasing the app tomorrow so good timing :)
How can I use it? You talked about a snapshot?

**Comment by f2prateek** [comment]
Yes, a snapshot is available on Sonatype, and I'm releasing it on central right now (will be available in a couple of hours). It's a breaking release, so you might have to change some code around, we'll have a migration guide up tomorrow as well.
