### ISSUE TITLE
identify(String userId) payload is missing userId attribute

### ISSUE THREAD

**Issue by alperkokmen** [segmentio/analytics-android#169]
It looks like the method that accepts a single `String` argument `userId` is not generating the proper response. In order to get `userId` (top-level attribute) set properly, I needed set `userId` in the trait argument.

```java
Analytics.with(context).identify("foobar");
//
// from Logs
// {IdentifyPayload{"userId="null",Traits{"userId":"POOPBUG","anonymousId":"f8fe55de-b516-439f-8088-edadafda7949"}}}
```

```java
Analytics.with(context).identify("foobar", new Traits().putValue("userId", "foobar"), null);
//
// from Logs
// {IdentifyPayload{"userId="foobar",Traits{"userId":"foobar","anonymousId":"f9f605cb-4e3e-42f8-969b-ae3fc3e24f48"}}}
```

**Comment by f2prateek** [comment]
That's weird, it just calls [`identify(userId, null, null);`](https://github.com/segmentio/analytics-android/blob/master/core/src/main/java/com/segment/analytics/Analytics.java#L255).

**Comment by alperkokmen** [comment]
right. i think the root cause here is second parameter (`newTraits`) being `null`. even though it gets set in [`traitsCache`](https://github.com/segmentio/analytics-android/blob/master/core/src/main/java/com/segment/analytics/Analytics.java#L283), in [`BasePayload` constructor](https://github.com/segmentio/analytics-android/blob/master/core/src/main/java/com/segment/analytics/BasePayload.java#L83), `contextCopy.traits().userId()` will return `null`.

**Comment by f2prateek** [comment]
Ah I see it now, thanks!

**Comment by joluet** [comment]
@f2prateek is there a workaround for this until the new version is released?

**Comment by joluet** [comment]
Ok, this seems to work, I just added traits when identifying the user. Is this right usage?:

```
final Traits traits = new Traits();
traits.put("someTrait", "someValue");
final Options options = new Options();
options.setTimestamp(new Date(System.currentTimeMillis()));

final String previousId = mSegment.identify(user.getId(), traits, options);
mSegment.alias(previousId, new Options());
```
