### ISSUE TITLE
2.5.3 tag missing

### ISSUE THREAD

**Issue by tigerpenguin** [segmentio/analytics-android#170]
On maven, I see 2.5.1 and 2.5.3, but no 2.5.2 - http://search.maven.org/#browse%7C-1694329187

On github, I see 2.5.1 tag and 2.5.2 tag, but no 2.5.3 tag. Did you mean to tag/release 2.5.3 on github?

**Comment by f2prateek** [comment]
Yes, there is actually no 2.5.2 release. On github the 2.5.2 tag should have been 2.5.3 (something wrong with our release script). I'll push up the 2.5.3 tag soon, sorry for the inconvenience.

**Comment by f2prateek** [comment]
2.5.3 should be up now.
