### ISSUE TITLE
Mixpanel: Support incrementing numerical events via options.increments

### ISSUE THREAD

**Issue by sperand-io** [segmentio/analytics-android#171]
https://segment.zendesk.com/agent/tickets/24168

![](https://cloudup.com/coW957Ys-pY+)

prior art: [analytics.js](https://github.com/segmentio/analytics.js-integrations/blob/master/lib/mixpanel/index.js#L171-L175) | [server-side](https://github.com/segmentio/integration-mixpanel/blob/master/lib/index.js#L252-L284) | [iOS](https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Mixpanel/SEGMixpanelIntegration.m#L81-L87) 

:)

**Comment by lambtron** [comment]
https://segment.zendesk.com/agent/tickets/24746

**Comment by lambtron** [comment]
https://segment.zendesk.com/agent/tickets/24863
