### ISSUE TITLE
Dev mode in Leanplum integration not working

### ISSUE THREAD

**Issue by joluet** [segmentio/analytics-android#186]
We want to use the Leanplum integration for A/B testing. But as the segmentio sdk always uses the Leanplum app id for production mode we're just not able to register new variables with Leanplum.

[Here](https://github.com/segmentio/analytics-android/blob/e06472312702c3f70ee7af85a2c977b6563a2db4/analytics-integrations/leanplum/src/main/java/com/segment/analytics/internal/integrations/LeanplumIntegration.java), you obviously commented the `setAppIdForDevelopmentMode` part. Why did you do that?

**Comment by f2prateek** [comment]
Why do you have to be in development mode to register new variables?

**Comment by joluet** [comment]
Ok, seems like I can create variables without the development mode. But it is still very inconvenient not to be able to use the development mode for testing. Please include it.

**Comment by f2prateek** [comment]
@joluet What do you need in development mode? Our recommendation is to simply setup a different Segment project with a different Leanplum project for development, and just swap those writeKeys in development and production mode.

**Comment by joluet** [comment]
Thanks, then we're do that.
