### ISSUE TITLE
$created for Mixpanel

### ISSUE THREAD

**Issue by adrienkohlbecker** [segmentio/analytics-android#209]
Hello,

At https://github.com/segmentio/analytics-android/blob/master/analytics-integrations/mixpanel/src/main/java/com/segment/analytics/internal/integrations/MixpanelIntegration.java#L55
It should be `$created`, not `$create`
According to https://mixpanel.com/docs/properties-or-segments/special-or-reserved-properties

**Comment by f2prateek** [comment]
good catch!
