### ISSUE TITLE
Multiple warnings in Android Studio when using segment ver 2.5.3

### ISSUE THREAD

**Issue by danish489** [segmentio/analytics-android#213]
This issue is similar to a previously reported one by phil-brown in Nov 2014 (https://github.com/segmentio/analytics-android/issues/120). I'm getting 99 warning as a result and that is bringing my launch time to 4 minutes as opposed to a few seconds. The previous issue is marked closed but we don't know what fixed it. 

Gradle file:

dependencies {
     [...]
    compile('com.segment.analytics.android:all:2.5.3') {
        transitive = true
    }
}

Output:

warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.leanplum.messagetemplates.q) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

x 99

**Comment by f2prateek** [comment]
There isn't anything we (or you) can do here. I've asked Leanplum to fix this but haven't heard back from them.
