### ISSUE TITLE
Mixpanel integration not using the special properties $email, $first_name but creating variables with slightly different names

### ISSUE THREAD

**Issue by somghosh** [segmentio/analytics-android#229]
I am sending the following code to identify the user, however the Mixpanel integration isn't populating the correct properties in People

            previousId = getAnalytics().identify(
                    String.valueOf(userData.getId()),
                    new Traits()
                            .putFirstName(userData.getFirstName())
                            .putLastName(userData.getLastName())
                            .putBirthday(userData.getAge())
                            .putEmail(userData.getEmail())
                            .putValue("Location", userData.getLocationCity())
                            .putBirthday(userData.getAge())
                            .putValue("IsFacebook", !loginData.getFacebookToken().equals(""))
                            .putName(userData.getFirstName() + " " + userData.getLastName()),
                    null);   

For example, mixpanel works on a $email, $first_name and $last_name, however I see new properties email, firstName and lastName showing up in Mixpanel instead of using the Mixpanel's special properties

https://mixpanel.com/docs/people-analytics/special-properties

![emandroid_prod___explore_people_-_mixpanel___mobile_analytics](https://cloud.githubusercontent.com/assets/5731118/6658106/f9e41360-cb56-11e4-93a7-87812c5721cf.png)

**Comment by f2prateek** [comment]
@somghosh This is fixed in the latest version, please make sure you're using that.

**Comment by somghosh** [comment]
Thanks @f2prateek . I just tried with the following code in my build.gradle

    // segment.io not all
    compile('com.segment.analytics.android:core:+') {
        transitive = true
    }
    // Add other dependencies as you want here
    compile 'com.google.android.gms:play-services:6.5.87'
    compile "com.mixpanel.android:mixpanel-android:4.5.3"

I am assuming this takes the last version of your repo by default. Still I dont see the special properties in ixpanel not getting filled up

**Comment by somghosh** [comment]
I checked that the library is 2.5.3 - which I believe is the last version

**Comment by f2prateek** [comment]
No, that is not the latest version. See https://github.com/segmentio/analytics-android/releases.

We've changed how we package integrations in the new version, you can read the new way to add Segment to your app here - https://segment.com/docs/libraries/android/quickstart/.

**Comment by somghosh** [comment]
Thanks @f2prateek - just noticing. I usually put the libraries/packages via gradle - I dont see a higher version than 2.5.3 on gradle yet

**Comment by somghosh** [comment]
Just seeing the change of name of the package! I was following the full-tutorial, not the quickstart one - hence the confusion. Maybe you should update it later when you get a bit. Many thanks

**Comment by f2prateek** [comment]
It is in the full documentation as well, just a little bit lower down (https://segment.com/docs/libraries/android/#custom-builds). Let me know if you see any outdated references.
