### ISSUE TITLE
Activity lifecycle methods blocking main thread

### ISSUE THREAD

**Issue by johnryan** [segmentio/analytics-android#231]
As far as I can tell whenever i start an activity a flurry of Segment events get fired off. Is this necessary? If not how can I disable? If it is, can it be performed on a background thread?

**Comment by f2prateek** [comment]
These are offloaded onto a background thread, and they cannot be disabled if you want integrations to work.

**Comment by f2prateek** [comment]
How are they blocking the main thread?

**Comment by johnryan** [comment]
Sorry about that...after further investigation it was something else happening at the same time (on the main thread that was causing issues). Thanks for the response.

**Comment by f2prateek** [comment]
Cool, feel free to let us know if you run into any other issues!
