### ISSUE TITLE
onIntegrationReady callback not called

### ISSUE THREAD

**Issue by emptyarray** [segmentio/analytics-android#255]
I am trying to access my Mixpanel instance as suggested here:

```java
analytics.onIntegrationReady(BundledIntegration.MIXPANEL, new Callback() {
  @Override public void onIntegrationReady(Object instance) {
    ((MixpanelAPI) instance).clearSuperProperties();
  }
});
```
There are two problem:

```onIntegrationReady``` does not exist on ```Callback```, only ```onReady```. This sounds like the docs are outdated. So I changed it to this:

```java
// this runs
analytics.onIntegrationReady(BundledIntegration.MIXPANEL, new Callback() {
  @Override public void onReady(Object instance) {
    // this never runs
    ((MixpanelAPI) instance).clearSuperProperties();
  }
});
```
```onReady``` never seems to run, so I cannot access the Mixpanel instance, which I need for a bunch of stuff.

Thanks for looking into it.

**Comment by emptyarray** [comment]
I solved this with Proguard rules: https://github.com/segmentio/analytics-android/issues/109

+1 for updating docs with Proguard.

**Comment by f2prateek** [comment]
Thanks, I've added a section on our FAQ.
