### ISSUE TITLE
Bypassing last seen on Mixpanel

### ISSUE THREAD

**Issue by somghosh** [segmentio/analytics-android#258]
Is there a way to do the following in the android library?

https://segment.com/docs/integrations/mixpanel/#bypass-last-seen-in-server-side-calls

You can bypass the automatic re-setting of the “Last Seen” date property by passing active with a value of false in the context object, as follows:

	analytics.identify(user_id='12345', traits={ 
	    'name': 'Frank'}, context={
	    'active': false
	    })

I couldnt find out how to past a context dictionary

**Comment by f2prateek** [comment]
If you're using the server side integration, you can add it to the global context dictionary (`analytics.getContext()`) for now. The bundled integration currently doesn't support this however.

**Comment by f2prateek** [comment]
@somghosh Btw why do you want to bypass a user from the mobile library? It makes sense in a server side context where you might be triggering events independent of user actions, but not on mobile right?

**Comment by somghosh** [comment]
Hi @f2prateek , this is a specific requirement. I have a code for identifying with the email on the App.onCreate(), which is also fired when a push notification is received on the phone. This makes App.onCreate() run, and it calls identify() which updates the last_seen in Mixpanel for that user, although the user didnt necessarily come back to the app - just received a push on the phone (that triggered this code)

Is there any update on including this feature in Segment? or can I directly use the Mixpanel library for this?

**Comment by f2prateek** [comment]
To clarify, in your Application's onCreate method you call `identify`. Even if you were to use the ignore_time property somehow via Segment, you wouldn't want that to always ignore the user's last seen property (since most times the onCreate is actually triggered by the user opening the app). So you'd have to wrap it in a check anyway, if I'm right?

```java 
void onCreate(...) {
  if (isPush()) {
    analytics.identify(..., new Traits().put("active", false));
  } else {
    analytics.identify(...);
  }
}
```

Could you just do this then? I don't think you'd want to really identify the user from a push notification anyway.

```java 
void onCreate(...) {
  if (isPush()) {
    // don't identify the user since this is a push notification
  } else {
    analytics.identify(...);
  }
}
```

**Comment by f2prateek** [comment]
@somghosh any updates? Does the above solution work for you?
