### ISSUE TITLE
How to add com.google.android.gms:play-services-analytics:7.0.0 to build.gradle

### ISSUE THREAD

**Issue by somghosh** [segmentio/analytics-android#295]
My code is as follows in build.gradle - I get the following message however, I can't seem to find the library  required on repositories. Can you tell me the line to add in build.gradle to add it correctly?

Error:Could not find com.google.android.gms:play-services-analytics:7.0.0.
Required by:
    em-android:app:unspecified > com.segment.analytics.android:analytics-integration-google-analytics:3.1.3

    compile('com.segment.analytics.android:analytics-core:3.1.3') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-mixpanel:3.1.3') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-google-analytics:3.1.3') {
        transitive = true
    }

**Comment by f2prateek** [comment]
Nothing special, just follow the instructions required to setup google play services. Most likely you'll need to make sure you've installed it correctly - https://cloudup.com/czDwnNQvLxg.

https://developer.android.com/sdk/installing/adding-packages.html and
https://developers.google.com/android/guides/setup might help.
