### ISSUE TITLE
Fatal Crash with Kahuna

### ISSUE THREAD

**Issue by arango** [segmentio/analytics-android#297]
Trying to get Kahuna push notifications working through Segment.  As soon as I added the project's GCM key to Segment, I am getting the following:

06-11 12:08:59.926  31826-31892/com.toplinegamelabs.dailymvp E/dalvikvm﹕ Could not find class 'com.kahuna.sdk.location.KahunaGeofenceRequester$1', referenced from method com.kahuna.sdk.location.KahunaGeofenceRequester.<init>
06-11 12:09:05.639  31826-31910/com.toplinegamelabs.dailymvp E/AndroidRuntime﹕ FATAL EXCEPTION: Timer-1
    Process: com.toplinegamelabs.dailymvp, PID: 31826
    java.lang.NoClassDefFoundError: com.google.android.gms.gcm.GoogleCloudMessaging
            at com.kahuna.sdk.GCMRegistrationManager$RegisterGCMPLayServicesTask.run(GCMRegistrationManager.java:278)
            at java.util.Timer$TimerImpl.run(Timer.java:284)

I have the google-services.json in my app directory.  Gradle dependencies currently looks like this:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:design:22.2.0'
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:gridlayout-v7:22.2.0'
    compile 'com.android.support:support-v4:22.2.0'
    compile 'com.squareup.retrofit:retrofit:1.8.0'
    compile 'com.jakewharton:butterknife:6.0.0'
    compile 'fr.baloomba:viewpagerindicator:2.4.2'
    compile 'com.squareup.picasso:picasso:2.4.0'
    compile 'com.facebook.android:facebook-android-sdk:3.20.0'
    compile 'com.squareup:otto:1.3.6'
    compile('com.segment.analytics.android:analytics:+@aar') {
        transitive = true
        exclude group: 'com.squareup.okhttp', module: 'okhttp'
    }
    compile('com.crashlytics.sdk.android:crashlytics:2.3.2@aar') {
        transitive = true;
    }
    compile 'com.astuetz:pagerslidingtabstrip:1.0.1'
}

I tried including com.google.android.gms:play-services-gcm:7.5.0 directly, but that gets collisions with, I'm assuming, segment.analytics.

**Comment by f2prateek** [comment]
Are you using proguard?

**Comment by arango** [comment]
No, this is just when building a debug build.

This seems to have fixed it, but not sure if there are other google play things I need to add to get things working:

    compile 'com.google.android.gms:play-services-gcm:7.5.0'
    compile 'com.google.android.gms:play-services-analytics:7.5.0'
    compile('com.segment.analytics.android:analytics:+@aar') {
        transitive = true
        exclude group: 'com.squareup.okhttp', module: 'okhttp'
        exclude group: 'com.google.android.gms'
    }

**Comment by f2prateek** [comment]
@TorreyKahuna might be able to help explain which Google Play dependencies are required by Kahuna.

**Comment by arango** [comment]
Need to be able to support Google Analytics, Kahuna, Mixpanel, and MobileAppTracking.

**Comment by arango** [comment]
Also, while I at least have it building now, I still can't push to it with Kahuna.   This look like about right for including in the Application onCreate?

        analytics.onIntegrationReady(Analytics.BundledIntegration.KAHUNA, new Analytics.Callback() {
            @Override
            public void onReady(Object instance) {
                KahunaAnalytics.onAppCreate(DailyMVPApplication.this, Constants.KAHUNA_ID, Constants.GOOGLE_SENDER_ID);
                KahunaAnalytics.setPushReceiver(KahunaPushReceiver.class);
            }
        });

Think of anything else I might need here?

**Comment by TorreyKahuna** [comment]
@arango You will need com.google.android.gms:play-services-gcm for push
and com.google.android.gms:play-services-location if you want to use Kahuna Region Monitoring.

The onAppCreate looks fine, do you have any logcat logs that I can take a peek at? The Kahuna SDK should register for Push when your app starts.

**Comment by arango** [comment]
Excellent.  I had gcm, but added location as well.

I didn't see much for Kahuna in the logs.  Just this:

06-11 15:06:09.741  13092-13126/? I/dalvikvm﹕ Failed resolving Lcom/kahuna/sdk/location/KahunaGeofenceRequester$1; interface 4462 'Lcom/google/android/gms/location/LocationListener;'
06-11 15:06:09.741  13092-13126/? W/dalvikvm﹕ Link of class 'Lcom/kahuna/sdk/location/KahunaGeofenceRequester$1;' failed
06-11 15:06:09.741  13092-13126/? E/dalvikvm﹕ Could not find class 'com.kahuna.sdk.location.KahunaGeofenceRequester$1', referenced from method com.kahuna.sdk.location.KahunaGeofenceRequester.<init>
06-11 15:06:09.741  13092-13126/? W/dalvikvm﹕ VFY: unable to resolve new-instance 4939 (Lcom/kahuna/sdk/location/KahunaGeofenceRequester$1;) in Lcom/kahuna/sdk/location/KahunaGeofenceRequester;
06-11 15:06:09.741  13092-13126/? D/dalvikvm﹕ VFY: replacing opcode 0x22 at 0x0003
06-11 15:06:09.741  13092-13126/? W/dalvikvm﹕ VFY: unable to find class referenced in signature (Lcom/google/android/gms/location/LocationListener;)
06-11 15:06:09.742  13092-13126/? W/dalvikvm﹕ VFY: unable to resolve static field 15164 (GeofencingApi) in Lcom/google/android/gms/location/LocationServices;
06-11 15:06:09.742  13092-13126/? D/dalvikvm﹕ VFY: replacing opcode 0x62 at 0x0006
06-11 15:06:09.742  13092-13126/? W/dalvikvm﹕ VFY: unable to resolve static field 15162 (API) in Lcom/google/android/gms/location/LocationServices;
06-11 15:06:09.742  13092-13126/? D/dalvikvm﹕ VFY: replacing opcode 0x62 at 0x000b
06-11 15:06:09.743  13092-13126/? I/dalvikvm﹕ Could not find method com.google.android.gms.location.LocationRequest.create, referenced from method com.kahuna.sdk.location.KahunaGeofenceRequester.onResult
06-11 15:06:09.743  13092-13126/? W/dalvikvm﹕ VFY: unable to resolve static method 31573: Lcom/google/android/gms/location/LocationRequest;.create ()Lcom/google/android/gms/location/LocationRequest;
06-11 15:06:09.744  13092-13126/? D/dalvikvm﹕ VFY: replacing opcode 0x71 at 0x0026
06-11 15:06:09.744  13092-13126/? I/dalvikvm﹕ Failed resolving Lcom/kahuna/sdk/location/KahunaGeofenceRequester$1; interface 4462 'Lcom/google/android/gms/location/LocationListener;'
06-11 15:06:09.744  13092-13126/? W/dalvikvm﹕ Link of class 'Lcom/kahuna/sdk/location/KahunaGeofenceRequester$1;' failed
06-11 15:06:09.744  13092-13126/? D/dalvikvm﹕ DexOpt: unable to opt direct call 0x8641 at 0x05 in Lcom/kahuna/sdk/location/KahunaGeofenceRequester;.<init>
06-11 15:06:09.745  13092-13126/? I/dalvikvm﹕ DexOpt: unable to optimize static field ref 0x3b3b at 0x39 in Lcom/kahuna/sdk/location/KahunaGeofenceRequester;.onResult


Push registration looks like it's working.  I can create a new user, they show up in the Kahuna dashboard with a push_enabled device, but I can't actually push to them - only in-app.

**Comment by TorreyKahuna** [comment]
@arango Can you share with me the username or device_id that you are testing with? I can take a look and see what's up with that user and why you can't push to them.

**Comment by arango** [comment]
username mvp30991
deviceID: 29b3648b-50f6-4154-95d6-8aae31baf692

**Comment by TorreyKahuna** [comment]
@arango You'll need to add your GCM API Key onto your Kahuna account. Log into your Kahuna Account and then go to settings. Scroll down until you see a header called "Push Authorization".

There you can copy and paste in your GCM API Key and then you'll be able to send Pushes to Android devices.

https://app.usekahuna.com/tap/getstarted/android/manual/

Step 2 in enabling push has those instructions for reference.

**Comment by arango** [comment]
By settings, you mean https://app.usekahuna.com/tap/#settings ?  Or is there some other settings page?

**Comment by TorreyKahuna** [comment]
yup, those settings

**Comment by arango** [comment]
Huh.  All I see there are App Settings.  Nothing for Push Authorization.

**Comment by TorreyKahuna** [comment]
@arango can you email it to support@kahuna.com?

You don't seem to have credentials for your kahuna account.
