### ISSUE TITLE
Mixpanel initializeWithIncrementsAndPeople test fails.

### ISSUE THREAD

**Issue by VicV** [segmentio/analytics-android#299]
Pretty frustrating that I have to disable mixpanel all over the place just to be able to run a full test. 

    
```
com.segment.analytics.internal.integrations.MixpanelTest > initializeWithIncrementsAndPeople FAILED
    java.lang.AssertionError at MixpanelTest.java:114
Ran lint on variant debug: 0 issues found
Ran lint on variant release: 0 issues found
```

**Comment by f2prateek** [comment]
Works for me and on the CI, you're probably not using Java 8?

**Comment by f2prateek** [comment]
Also slightly related, you can just cd into the taplytics directory and run tests only for Taplytics.

`cd analytics-integrations/taplytics` & `../../gradlew build`
