### ISSUE TITLE
Localytics: 'Track' does not recognize 'revenue' property correctly on Android

### ISSUE THREAD

**Issue by eriklarson** [segmentio/analytics-android#301]
On the iOS version on Segment, the track event checks to see if there is a 'revenue' present
https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Localytics/SEGLocalyticsIntegration.m#L127-L133

On the Android version, it doesn't:
https://github.com/segmentio/analytics-android/blob/21161a10e8b8b08f84c6331b80af005e766a0467/analytics-integrations/localytics/src/main/java/com/segment/analytics/internal/integrations/LocalyticsIntegration.java#L127-L133

Without this, it's not possible to track monetary events in Localytics.

**Comment by f2prateek** [comment]
It looks like a.js doesn't either - https://github.com/segment-integrations/analytics.js-integration-localytics/blob/master/lib/index.js#L118

@sperand-io what would the right behaviour here be? I'm inclined to think iOS is correct.
