### ISSUE TITLE
Disabling/Enabling specific integrations is not working.

### ISSUE THREAD

**Issue by GuillaumeDelente** [segmentio/analytics-android#315]
According to the doc, it should be possible to enable/disable bundled integrations for a specific call using `Options` : https://segment.com/docs/libraries/android/#options

However, it seems that the event is getting sent to all the integrations, no matter what's in `Options`.
Here is how I am disabling Mixpanel for example :
```
Options mixpanelDisabled = new Options();
mixpanelDisabled.setIntegration(Analytics.BundledIntegration.MIXPANEL, false);
analytics.track("event", new Properties(), mixpanelDisabled);
```

**Comment by f2prateek** [comment]
Could you enable logging and send us the logs, either here or to prateek@segment.com?

**Comment by GuillaumeDelente** [comment]
@f2prateek Here is the logcat :
```
07-23 11:27:54.957     D/Segment﹕ Created payload TrackPayload{"event}.
07-23 11:27:54.958     D/Segment﹕ Running TrackPayload{"event} on 3 integrations.
07-23 11:27:54.959     D/Segment﹕ Took 1 ms to run action TrackPayload{"event} on Google Analytics.
07-23 11:27:54.960     D/Segment﹕ Took 0 ms to run action TrackPayload{"event} on Mixpanel.
07-23 11:27:54.962     D/Segment﹕ Took 0 ms to run action TrackPayload{"event} on Segment.io.
07-23 11:27:54.985     D/Segment﹕ Enqueued TrackPayload{"event} payload. Queue size is now : 1.
```

**Comment by f2prateek** [comment]
@GuillaumeDelente how did you determine that an event was sent to an integration or not? From looking at the actual tool or just from these logs?

Our Android logs don't actually indicate whether an integration was disabled or not. e.g. if you disable Mixpanel from options as in your example, you'll still see `Took 0 ms to run action TrackPayload{"event} on Mixpanel.`

**Comment by GuillaumeDelente** [comment]
@f2prateek the events are showing in the disabled integration's dashboard.
<img width="518" alt="screen shot 2015-07-23 at 11 40 06 am" src="https://cloud.githubusercontent.com/assets/447889/8854773/a2a4a1b6-312f-11e5-85ae-54665acfe652.png">

**Comment by f2prateek** [comment]
@GuillaumeDelente could you enable verbose logging and send the entire log (not just Segment, but the integrations as well)?

**Comment by GuillaumeDelente** [comment]
@f2prateek segment is not logging anything else, nor are the bundled integrations.

**Comment by GuillaumeDelente** [comment]
@f2prateek actually GA is logging stuff but not mixpanel, so I disabled Google Analytics instead :  

        Options noGA = new Options();
        noGA.setIntegration(Options.ALL_INTEGRATIONS_KEY, true);
        noGA.setIntegration(Analytics.BundledIntegration.GOOGLE_ANALYTICS, false);
        Properties props = new Properties();
        props.put("page name", pageName);
        analytics.track("event", props, noGA);

And this is what is getting logged : 
```
app.debug V/GAV4﹕ Thread[GAThread,5,main]: connecting to Analytics service
app.debug V/GAV4﹕ Thread[main,5,main]: service connected, binder: android.os.BinderProxy@b53a7f5
app.debug V/GAV4﹕ Thread[main,5,main]: bound to service
app.debug V/GAV4﹕ Thread[GAThread,5,main]: connect: bindService returned true for Intent { act=com.google.android.gms.analytics.service.START cmp=com.google.android.gms/.analytics.service.AnalyticsService (has extras) }
app.debug V/GAV4﹕ Thread[main,5,main]: Connected to service
app.debug I/GAV4﹕ Thread[GAThread,5,main]: No campaign data found.
app.debug V/GAV4﹕ Thread[GAThread,5,main]: Initialized GA Thread
app.debug V/GAV4﹕ Thread[GAThread,5,main]: Loaded clientId
app.debug V/GAV4﹕ Thread[GAThread,5,main]: putHit called
app.debug V/GAV4﹕ Thread[GAThread,5,main]: Sending hit to service   PATH: https:  PARAMS: sr=1080x1776,  ht=$,  cd=screen_my_kids,  _u=.nKK-AL,  cid=$,  av=1.3.7,  aip=0,  a=$,  v=1,  an=debug,  ul=en-us,  t=screenview,  tid=$,  aid=app.debug,
app.debug V/GAV4﹕ Thread[GAThread,5,main]: putHit called
app.debug V/GAV4﹕ Thread[GAThread,5,main]: Sending hit to service   PATH: https:  PARAMS: sr=1080x1776,  ht=$,  _u=.KyAAAAAL,  ec=All,  cid=$,  ev=0,  av=1.3.7,  aip=0,  a=$,  v=1,  an=$,  ul=en-us,  t=event,  tid=$,  ea=event,  aid=app.debug,
```

The second hit is the event that shouldn't be sent by GA.

**Comment by f2prateek** [comment]
@GuillaumeDelente I can't reproduce this in our sample app (https://github.com/segmentio/analytics-android/commit/4fe939fa362c6bcf4f0302f8de0dc7e09bc6b579). The first event in the sample makes it to Mixpanel but not the second.

Can you send me a reproducible case in this repo and let me know which Segment project this is for?

**Comment by GuillaumeDelente** [comment]
@f2prateek I've checked out https://github.com/segmentio/analytics-android/commit/4fe939fa362c6bcf4f0302f8de0dc7e09bc6b579 and changed the segment write key to point to my segment project.
The two events are making it to mixpanel.

**Comment by f2prateek** [comment]
@GuillaumeDelente Can you send an email to friends@segment.com and cc prateek@segment.com? We'll check it out.

**Comment by f2prateek** [comment]
Closing due to lack of response.
