### ISSUE TITLE
Dex limit

### ISSUE THREAD

**Issue by kgpmurray** [segmentio/analytics-android#325]
Is there a way to cut down the dependancys this library downloads as it is pushing my app over the Dex limit and the multidex library is causeing further issues.

**Comment by f2prateek** [comment]
There are no dependencies in the core library.

You can eliminate unused bundled integrations by following the instructions here: https://segment.com/docs/libraries/android/#custom-builds

**Comment by f2prateek** [comment]
Simply switching to this (see below) will cut down the size significantly.
```
compile('com.segment.analytics.android:analytics-core:+') {
  transitive = true
}
```

**Comment by kgpmurray** [comment]
Thank you,
