### ISSUE TITLE
AnonymousId changes when upgrading from 0.6.10 to 3.1.1 - causes Amplitude to think this is a new User.

### ISSUE THREAD

**Issue by kellyfj** [segmentio/analytics-android#326]
One underlying issue is that in Segment 0.6.10  the anonymous Id is stored as a shared preference under this key ``` "session.id"```

However 3.1.1 Segment is looking up based on this key

 ``` private static final String ANONYMOUS_ID_KEY = "anonymousId"; ```

And therefore the customer's original Anonymous Id is being overlooked and a new one is being created, making the customer look like a new customer to Amplitude.

This (I think) will only occur in the flow where 
1) Identify is not used 
2) And so userId = anonymousId

A related issue perhaps is that the name of the Shared Preferences file has changed from 
```
public SimpleStringCache(Context context, String cacheKey) { 
		String prefKey = Constants.PACKAGE_NAME + "." +  context.getPackageName();
		
		preferences = context.getSharedPreferences(
				 prefKey, android.content.Context.MODE_PRIVATE);
```

to 

```
/** Returns a shared preferences for storing any library preferences. */
  public static SharedPreferences getSegmentSharedPreferences(Context context) {
    return context.getSharedPreferences("analytics-android", MODE_PRIVATE);
  }

```

and so I *think* that any shared preferences in 0.6.10 will be lost in an upgrade to 3.1.1? @f2prateek can you confirm this last point? Thanks!

**Git History links**
*anonymousId vs session.id*
0.6.10 : <a href="https://github.com/segmentio/analytics-android/blob/71d8ba3d6de5159f88e87e89b1da3b03e1bfae64/src/io/segment/android/Constants.java#L57">Constants.java</a> and <a href="https://github.com/segmentio/analytics-android/blob/71d8ba3d6de5159f88e87e89b1da3b03e1bfae64/src/io/segment/android/cache/SessionIdCache.java#L13">SessionIdCache.java</a>
vs 
3.1.1 <a href="https://github.com/segmentio/analytics-android/blob/447d7af39f293274df80516bc1bc9d276d41aa5d/analytics-core/src/main/java/com/segment/analytics/Traits.java#L56">Traits.java<a>

*SharedPreferences File Name*
0.6.10 : <a href="https://github.com/segmentio/analytics-android/blob/71d8ba3d6de5159f88e87e89b1da3b03e1bfae64/src/io/segment/android/cache/SimpleStringCache.java#L23">SimpleStringCache.java</a>
vs 
3.1.1 : <a href="https://github.com/segmentio/analytics-android/blob/447d7af39f293274df80516bc1bc9d276d41aa5d/analytics-core/src/main/java/com/segment/analytics/internal/Utils.java#L156">Utils.java</a>

**Comment by f2prateek** [comment]
@kellyfj yes, those preferences are lost in the upgrade. This will affect users that have not been identified.
