### ISSUE TITLE
Throw early for null keys

### ISSUE THREAD

**Issue by imminent** [segmentio/analytics-android#327]
We are getting the following stacktrace from Segment related to the mixpanel integration:

0 java.lang.NullPointerException: key == null
1 at org.json.JSONObject.<init>(JSONObject.java:136)
2 at com.segment.analytics.ValueMap.toJsonObject(ValueMap.java:323)
3 at com.segment.analytics.internal.integrations.MixpanelIntegration.event(MixpanelIntegration.java:179)
4 at com.segment.analytics.internal.integrations.MixpanelIntegration.track(MixpanelIntegration.java:170)
5 at com.segment.analytics.IntegrationOperation$10.run(IntegrationOperation.java:171)
6 at com.segment.analytics.IntegrationManager.run(IntegrationManager.java:391)
7 at com.segment.analytics.IntegrationManager.performEnqueue(IntegrationManager.java:371)
8 at com.segment.analytics.IntegrationManager.performEnqueue(IntegrationManager.java:366)
9 at com.segment.analytics.IntegrationManager$IntegrationManagerHandler.handleMessage(IntegrationManager.java:470)
10 at android.os.Handler.dispatchMessage(Handler.java:102)
11 at android.os.Looper.loop(Looper.java:135)
12 at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by imminent** [comment]
@f2prateek This isn't exactly the same stack trace as the other issue I mentioned, but they're very similar (null key vs null value).

**Comment by f2prateek** [comment]
Ah interesting. I actually prefer it if we crash for a null key, I can't think of a circumstance when there is a genuine need to use it, it's always a bad input.

**Comment by imminent** [comment]
If it's going to crash, fail early. It should raise an exception at entry,
otherwise it's too late to know where that null came from.

**Comment by f2prateek** [comment]
Yup I agree, just need to research a bit more to confirm that would be the right behaviour.

**Comment by f2prateek** [comment]
Thinking more about this, an dI don't think it makes sense for us to iterate over the entire map to check just for null keys. If we had more validations to do it would make sense, but otherwise it's best to avoid this - especially since it only affects integrations that use `JSONObject`.
