### ISSUE TITLE
Transaction Revenue not getting sent to Google Analytics

### ISSUE THREAD

**Issue by eriklarson** [segmentio/analytics-android#343]
Our Google Analytics product purchase data is getting passed to google analytics, but the transaction level data is not.

Looking at the code, it doesn't look like this event is getting called:
https://github.com/segmentio/analytics-android/blob/master/analytics-integrations/google-analytics/src/main/java/com/segment/analytics/internal/integrations/GoogleAnalyticsIntegration.java

For either way Google Analytics Ecomemerce events are implemented (original or enhanced), there is supposed to be a transaction revenue or total revenue field associated with the transaction.  This is not seem to be getting sent from what I can tell.  
https://developers.google.com/analytics/devguides/collection/android/v4/ecommerce
https://developers.google.com/analytics/devguides/collection/android/v4/enhanced-ecommerce

This does work in the Segment iOS implementation.  Please fix ASAP.

**Comment by f2prateek** [comment]
Can you share some more details? What is your tracking code? What event name are you using? What properties are you sending?

**Comment by eriklarson** [comment]
There is one Segment.io event that passes transaction revenue data.  It is the 'Completed Order' event.

The bug is in the Android Segment implementation of Google Analytics ecommerce events. Check out the iOS implementation here:
Line 158:
https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/GoogleAnalytics/SEGGoogleAnalyticsIntegration.m

Then look at your Android implementation (160-162)
https://github.com/segmentio/analytics-android/blob/master/analytics-integrations/google-analytics/src/main/java/com/segment/analytics/internal/integrations/GoogleAnalyticsIntegration.java

You never pass revenue.  You also don't pass tax or shipping.   This means no Android user would have any transaction level revenue show up in their Google Analytics account using this library.

To me, this seems like a very large bug that I'm surprised wasn't caught in QA.
