### ISSUE TITLE
Screen event getting triggered multiple times on Mixpanel

### ISSUE THREAD

**Issue by abhinav-koppula** [segmentio/analytics-android#383]
Hi,

I have mixpanel integration turned on in Segment.
I am firing a screen event using the following syntax:
Analytics.with(context).screen("Home", "Home", null);
On the debugger it shows the following: 
Home Home - analytics.screen("Home", "Home", new Properties());

For some reason, on Mixpanel, it shows the following:
Viewed Home Screen
Viewed Home Home Screen
Loaded a Screen

I wanted to know why multiple events are being fired on Mixpanel for only 1 event on Segment.

**Comment by f2prateek** [comment]
Our server side integration will send three distinct events for this — one event uses the category and one uses the name, and one is a generic event name. https://github.com/segmentio/integration-mixpanel/blob/master/lib/index.js#L191


I'll need to research a bit more why the server side sends it 3 times.

As a quick fix, you can turn off the setting for `trackCategorizedPages` and the `trackAllPages` option, and you'll see only one event.

**Comment by f2prateek** [comment]
Moved to https://github.com/segmentio/integration-mixpanel/issues/10
