### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by nizamcs** [segmentio/analytics-android#384]
We are maintaining two versions of applications, one with segment library and another without segment library for Android2.3 support.
Recently, I came across the following issue:
```
 java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:792)
       at java.util.HashMap$EntryIterator.next(HashMap.java:829)
       at java.util.HashMap$EntryIterator.next(HashMap.java:827)
       at android.os.Parcel.writeMapInternal(Parcel.java:589)
       at android.os.Bundle.writeToParcel(Bundle.java:1619)
       at android.os.Parcel.writeBundle(Parcel.java:605)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2247)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:2915)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4898)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
This is a 70% reproducible issue, but not seen in the build without segment library.  The scenario is,
I've two Activity with segment screen methods in onCreate().
I switch between these Activity repeatedly.
Above crash occurs at some point.
Also, befor the crash, I noticed some logs like
```
MoEHelper: onPause callback not called: ***.InitializationActivity.
MoEHelper: onPause callback not called: ***.MainActivity
```
Please note that, for testing, I used Samsung s3 (Android4.1.2) & Samsung s3 (Android 4.3).

**Comment by Atrix1987** [comment]
@nizamcs you can ignore the onPause logs, I have put it in debug mode and ran it and it does get called. The state gets reset and so you see the logs. This is just a log and will affect no functionality.

@f2prateek since segment-android puts lifecycle callbacks in a queue and runs it asynchronously can that be the cause of this issue ? Theoretically it can cause a ConcurrentModificationException right ?

also strangely for me in `com.segment.analytics.android:analytics-integration-moengage:3.3.0` `MoEngageIntegration#onActivityCreated` was not getting called. Since in 3.3.0 `MoEHelper` was initialized in onCreate I am getting a crash. But thats changed in 3.4.0. Still this crash should not have happened.

```java
D/Segment: Created payload ScreenPayload{name="Landing Screen,category="Landing"}.
D/Segment: Initializing integrations with {MoEngage={apiKey=XXIMMSH5H67C3T9KBHB}, Segment.io={apiKey=xMXXeCwurQ4yYXiaHlredqVC}}.
D/Segment: Initializing integration MoEngage with settings {apiKey=XXIMMSH5H67C3T9KBHB}.
D/Segment: Initializing integration Segment.io with settings {apiKey=xMXXeCwurQ4yYXiaHlredqVC}.
D/Segment: Running ScreenPayload{name="Landing Screen,category="Landing"} on 2 integrations.
D/Segment: Took 0 ms to run action ScreenPayload{name="Landing Screen,category="Landing"} on MoEngage.
D/Segment: Took 0 ms to run action ScreenPayload{name="Landing Screen,category="Landing"} on Segment.io.
D/Segment: Running Activity Started on 2 integrations.
E/AndroidRuntime: FATAL EXCEPTION: SegmentAnalytics-IntegrationManager
E/AndroidRuntime: Process: com.moengage.segmentdemo, PID: 13532
E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.moe.pushlibrary.MoEHelper.onStart(android.app.Activity)' on a null object reference
E/AndroidRuntime:     at com.segment.analytics.internal.integrations.MoEngageIntegration.onActivityStarted(MoEngageIntegration.java:78)
E/AndroidRuntime:     at com.segment.analytics.IntegrationOperation$2.run(IntegrationOperation.java:60)
E/AndroidRuntime:     at com.segment.analytics.IntegrationManager.run(IntegrationManager.java:391)
E/AndroidRuntime:     at com.segment.analytics.IntegrationManager.performEnqueue(IntegrationManager.java:371)
E/AndroidRuntime:     at com.segment.analytics.IntegrationManager$IntegrationManagerHandler.handleMessage(IntegrationManager.java:467)
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime:     at android.os.HandlerThread.run(HandlerThread.java:61)
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Segment: Enqueued ScreenPayload{name="Landing Screen,category="Landing"} payload. Queue size is now : 3.
```
Running on Nexus 5 Marshmallow

**Comment by f2prateek** [comment]
@Atrix1987 That wouldn't be the cause because those operations aren't accessed concurrently, they're dispatched to a single thread. The only time they are not accessed on that thread is when calling shutdown (@nizamcs are you using shutdown?).

**Comment by Atrix1987** [comment]
@f2prateek but Segment code and the app code gets processed asynchronously right ? In that case it might be possible isn't it ?

**Comment by f2prateek** [comment]
If something else if using the bundle outside of Segment, or if one of the sdks internally offload it to a background thread for processing and another SDK doesn't (or offloads it a different thread), then yes.

It's unlikely in this case that is issue, because there isn't a bundle associated with the `onStop` method, which are the 2 culprits in the stack trace.

**Comment by Atrix1987** [comment]
I see bundle operations in @nizamcs 's code. Not sure of other libs but his own code.
`ActivityManagerNative` does perform bundle operation.

Since segment lifecycle callbacks are non-blocking; `onStart` in Segment lib and onStop in Activity main can happen if the queue is not processed quickly. 

@nizamcs can you enable the verbose debugging mode for segment using
`.logLevel(Analytics.LogLevel.VERBOSE)` as mentioned in the debugging docs.
The library logs times for each task. 

@f2prateek also I would mention this happens only when @nizamcs performs repeated activity transitions A -> B -> A. After about 3-4 minutes of continuously doing so it crashes is what @nizamcs and I did to reproduce the issue

**Comment by nizamcs** [comment]
Hi,

PFA the full catlog with Analytics.LogLevel.VERBOSE enabled.
Also, it took 3-4 minutes because it was in debug mode. Usually the crash
occurs within one minute.

Regards,



*Nizam CS*

*Senior Software Engineer*

Email: nizam.ls@accedo.tv

www.accedo.tv

**Comment by f2prateek** [comment]
@nizamcs just so we're clear, using only the segment library without any integrations didn't crash your app, right? This would suggest that the bug is from one of our partner SDKs, not Segment.

**Comment by Atrix1987** [comment]
**UPDATE:**
@f2prateek: `onSaveInstance` is getting called in Segment and at the same time `onStop` is called on the UI Thread. In `onSavedInstance`, we add a flag (for not tracking the same screen twice, storing inapps, etc).
This causes `ConcurrentModificationException` in onStop in `ActivityManagerNative` which writes to the `Bundle`. 
This is the reason why I specified,  Activity Callbacks should always be called on UI Thread and not on a separate thread.

```java
D/MoEngage_v5308: MoEHelper:onSaveInstanceState-- saving state
D/Segment: Took 1 ms to run action Activity Save Instance on MoEngage.
D/Segment: Took 0 ms to run action Activity Save Instance on Segment.io.
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x415222a0)
D/dalvikvm: GC_CONCURRENT freed 2140K, 5% free 54035K/56839K, paused 6ms+14ms, total 139ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 92ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 127ms
D/dalvikvm: GC_CONCURRENT freed 1889K, 5% free 54194K/56839K, paused 4ms+11ms, total 110ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 96ms
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: java.util.ConcurrentModificationException
E/AndroidRuntime:     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:792)
E/AndroidRuntime:     at java.util.HashMap$EntryIterator.next(HashMap.java:829)
E/AndroidRuntime:     at java.util.HashMap$EntryIterator.next(HashMap.java:827)
E/AndroidRuntime:     at android.os.Parcel.writeMapInternal(Parcel.java:589)
E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1619)
E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:605)
E/AndroidRuntime:     at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2247)
E/AndroidRuntime:     at android.app.ActivityThread$StopInfo.run(ActivityThread.java:2915)
E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4898)
E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteIni
```

**Comment by f2prateek** [comment]
We can move it to the UI thread for sure, I haven't seen a problem with any other integrations in calling it on a background thread though.

**Comment by nizamcs** [comment]
What will be the implication of moving it to the UI thread? It will hit on performance, right?

**Comment by f2prateek** [comment]
Not really, since if you were to integrate natively you'd make those calls it on the UI thread as well; so it's no worse than that. And we'll still do it asynchronously, so it's less likely to interfere with a more crucial UI task like animations.

**Comment by Atrix1987** [comment]
@f2prateek you don't see any problem with any other integrations because most of them do not override `onActivitySaveInstance`. @nizamcs moving lifecycle callbacks should not hit any performance. Ideally lifecycle callbacks should be a blocking call. Think of it this way, your activity should not resume until `onResume` has finished

**Comment by f2prateek** [comment]
We might be able to make it a blocking call, but since integrations are initialized asynchronously, this won't always be possible. 

Like what happens when the integrations aren't initialized and we get an activityStop? It's only really a problem on the first launch of the app after an install since we don't have any cached settings, but we can't really block the activity from finishing until we can initialize the integrations.

**Comment by f2prateek** [comment]
And alose note that because the calls would be asynchronous (but on the UI thread), we might have a case where application code is processing onStop, but the integrations still haven't processed the onSaveInstance call.

**Comment by nizamcs** [comment]
Hi, any updates here? @f2prateek so moving to UI thread will cause the same/another issue? @Atrix1987 please share your thoughts.

**Comment by Atrix1987** [comment]
So @f2prateek you mean to say if an app is doing bundle manipulation (which is not uncommon in android) and is also using segment, then crash can happen.

**Comment by f2prateek** [comment]
If it happens off the main thread, then yes. We've made changes to our library so that it only calls integrations on the main thread, but we can't control what integrations are doing in their own libraries.

**Comment by f2prateek** [comment]
@nizamcs You can try the new releases:https://github.com/segmentio/analytics-android/wiki/Packaged-Integrations.

You'll need:
```groovy
repositories {
  mavenCentral()
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

dependencies {
  compile 'com.segment.analytics.android:analytics-core:4.0.0-SNAPSHOT'
  compile('com.segment.analytics.android.integrations:moengage:1.0.0-SNAPSHOT') {
    transitive = true
  }
}
```

And in your builder.

```java
Analytics analytics = new Analytics.Builder(context, writeKey)
  .use(MoEngageIntegration.FACTORY)
  .build();
```

**Comment by f2prateek** [comment]
No need to specify snapshot anymore as well.

**Comment by nizamcs** [comment]
Thank you All. @f2prateek please guide me to specify library without snapshot. 
Is it like,
```
repositories {
  mavenCentral()
}

dependencies {
  compile 'com.segment.analytics.android:analytics:+'
  compile('com.segment.analytics.android.integrations:moengage:1.0.0') {
    transitive = true
  }
}
```

**Comment by f2prateek** [comment]
Yes.

**Comment by rjhashlearn** [comment]
@f2prateek The toast message with <activity> did not call MoEHelper.onPause(this) still apears after upgrading the bundled integration to 1.0.0. Was that intentionally left behind ?

**Comment by f2prateek** [comment]
@rjhashlearn I'm not sure what issue you are referring to, but could you open with more details in this repository https://github.com/segment-integrations/analytics-android-integration-moengage?

**Comment by rjhashlearn** [comment]
@f2prateek I was referring to what @nizamcs mentioned in this thread regarding the logs found - 

```
MoEHelper: onPause callback not called: ***.InitializationActivity.
MoEHelper: onPause callback not called: ***.MainActivity
```
Attaching screnshot
![img_save](https://cloud.githubusercontent.com/assets/15018392/14664310/8184af7e-06e7-11e6-9008-e16c38975b1d.jpg)

This seems to be appearing in all activities
