### ISSUE TITLE
Update Localytics Release

### ISSUE THREAD

**Issue by WesleyDRobinson** [segmentio/analytics-android#386]
Ticket open re: crashing issues with earlier releases.
iOS integrations is on release 3.5.1

**Comment by f2prateek** [comment]
What's the newest version for Android?

**Comment by WesleyDRobinson** [comment]
Current Android version is 3.5.0 according to the [Localytics SDK Changelog](http://docs.localytics.com/#Dev/sdk-changelog.html)
![](https://cloudup.com/cYQG2vkJKD4+)

**Comment by f2prateek** [comment]
Thanks! We'll definitely do this once I split out the integrations to their own repos.

**Comment by f2prateek** [comment]
Added in https://github.com/segment-integrations/analytics-android-integration-localytics
