### ISSUE TITLE
NPE when passing null value for traits in identify

### ISSUE THREAD

**Issue by abhinav-koppula** [segmentio/analytics-android#387]
I have the following code:

```
Traits traits = new Traits();
traits.putValue("foo", null);
traits.putValue("bar", null);
Analytics.with(context).identify(uuid, traits, null);
```

Basically I would want to unset some properties which had been set in the first identify event. However on executing the above code, I get a NPE. Am I doing anything wrong?

**Comment by f2prateek** [comment]
Where is the NPE? Can you share the stack trace?

**Comment by f2prateek** [comment]
Also, what version of the library is this?

**Comment by mbernier85** [comment]
I'm getting issue too

here is a stack trace
