### ISSUE TITLE
Remove dependency to Json

### ISSUE THREAD

**Issue by mbernier85** [segmentio/analytics-android#392]
Dependency org.json:json:20131018 is ignored for Debug as it may be conflicting with the internal version provided by Android.

I added this for now to solve this error
exclude group: 'org.json', module: 'json'

**Comment by f2prateek** [comment]
Which version? We don't have that dependency in the library.

**Comment by mbernier85** [comment]
Version 3.4

I just added the library to the project, and now I have warnings during build

    //segment.io
    compile('com.segment.analytics.android:analytics:3.4.0@aar') {
        transitive = true
        exclude group: 'org.json', module: 'json'
    }

**Comment by f2prateek** [comment]
That doesn't mean it's from our library. It's probably coming from one of the integrations that this bundles. You can see our core library don't have any dependencies (https://repo1.maven.org/maven2/com/segment/analytics/android/analytics-core/3.4.0/analytics-core-3.4.0.pom). You can run `./gradlew dependencies` to check where it's coming from (most likely Tapstream).
