### ISSUE TITLE
Why does `put` return `Object` where `putEmail` returns Trait?

### ISSUE THREAD

**Issue by FreakTheMighty** [segmentio/analytics-android#399]
It seems odd that `putEmail`, `putFirstName` etc, returns a `Traits`, instance, but `put` returns `Object`. This makes it so that we can't chain with `put`. For example, this doesn't work.
```Java
new Traits().put("custom", "value").putFirstName("first").putLastName("last");
```

**Comment by f2prateek** [comment]
`put` is a method defined by the [map interface](http://docs.oracle.com/javase/7/docs/api/java/util/Map.html#put(K,%20V)), which by contract is meant to return the previously defined value for the given key. We can't just change it return whatever we want.

There's a method called `putValue` that does what you're looking for.
