### ISSUE TITLE
java.lang.StackOverflowError when build with Localytics integration

### ISSUE THREAD

**Issue by featalion** [segmentio/analytics-android#402]
Hi,

I have an issue during build with Localytics integration.
I add the next lines into `analytics/build.gradle`:

```
repositories {
    jcenter()
    maven { url 'http://maven.localytics.com/public' }
}

dependencies {
  compile('com.segment.analytics.android.integrations:localytics:+') {
    transitive = true
  }
  compile('io.branch.segment.analytics.android.integrations:library:+') {
    transitive = true
  }
}
```

Gradle downloaded all required libraries, but is failed to build the library:

```
$ gradle build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':analytics'.
> Failed to notify project evaluation listener.
   > java.lang.StackOverflowError (no error message)
   > Cannot access first() element from an empty List

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.401 secs
```

Logs:
[`gradle build --stacktrace`](http://pastebin.com/ehpCDPrv)
[`gradle build --debug`](http://pastebin.com/8MJLUv65)
[`gradle build --info`](http://pastebin.com/7Wgbbtc1)

Any help is appreciated. Thanks in advance!

**Comment by f2prateek** [comment]
Can you share a sample project that demonstrates this? Also does this work without the localytics library? What if you pin the versions and explicitly declare the Segment dependency?

**Comment by featalion** [comment]
What do you mean by "sample project"? I tried to build right from this repository. Our Android app is based on Unity3D engine, so that it requires binary libraries instead of building it as part of the whole project.

FYI: we resolved the issue by building all dependencies on our own and do not use Localytic's Maven repo.
