### ISSUE TITLE
new libraries appending "Segment.io: false" 

### ISSUE THREAD

**Issue by hankim813** [segmentio/analytics-android#406]
We started appending this in our newest version inside the `integrations` object to denote that you have bundled the Segment integration. Segment integration is bundled by default when you install the mobile library so this piece is only relevant in debugging process for Segment success engineers... but causes confusion to our customers.

The only time that would be `true` is if a user manually stripped that integration using manual classes... which is probably not too often since it would mean that you can't send server side events.

I would urge that we revert back to our older version's behavior and just leave that out to prevent customers from being confused.

@f2prateek @sperand-io

**Comment by RamIndani** [comment]
@f2prateek  @hankim813 After this change only Segment.io will not be shown under Integrations object and all other integrations like AppsFlyer will show "AppsFlyer:false" even though they are enabled under integration tab.

**Comment by RamIndani** [comment]
@f2prateek  @hankim813 After this change only Segment.io will not be shown under Integrations object and all other integrations like AppsFlyer will show "AppsFlyer:false" even though they are enabled under integration tab.

**Comment by f2prateek** [comment]
@RamIndani that is by design. If we didn't do that, the server would send those events via the server side integrations even though the client side integration handled them.

**Comment by RamIndani** [comment]
@f2prateek Thank you for the response, now it's more easy to understand and explain why it shows false under Integration.
