### ISSUE TITLE
the debugger console receive many "identify" method at same time 

### ISSUE THREAD

**Issue by wonTonx** [segmentio/analytics-android#409]
I put the identify method in the Application Class and I use MultiDex, Is it the reason that method run that many times?

What i see is like that
![image](https://cloud.githubusercontent.com/assets/4646750/12773718/35f5395c-ca79-11e5-9a89-73b3e1a7d487.png)

**Comment by f2prateek** [comment]
Without any code or logs it's hard to tell what's at fault here. Most likely you're calling identify multiple times.

**Comment by wonTonx** [comment]
the odd place it when this happen the only method sent is identify , other like track I use will not be seeing on the debugger console While other model is working fine that the identify is sent once and other event track will show

**Comment by f2prateek** [comment]
Needs more logs.
