### ISSUE TITLE
Possible NullPointerException in IntegrationOperation

### ISSUE THREAD

**Issue by aaron112** [segmentio/analytics-android#415]
There is a possible NullPointerException which was just introduced on 4.0.6. See https://github.com/segmentio/analytics-android/commit/a10246417e740b8e5398a8c2a9e61637a0aafd7a#diff-56c6e264399fe3e6f141ddbdbdbb7ab9R189: `eventPlan` might be null.

**Comment by f2prateek** [comment]
If you check line 181 in the diff - we check if the event plan is null `if (isNullOrEmpty(eventPlan)) {` before continuing.

**Comment by f2prateek** [comment]
I see, I forgot to return. Thanks!

**Comment by f2prateek** [comment]
Fixed in https://github.com/segmentio/analytics-android/commit/21ec037f060baacef416a7ddf7fb6bf0b0cbab5c

**Comment by aaron112** [comment]
Thanks!
