### ISSUE TITLE
Library suddenly crashes today.

### ISSUE THREAD

**Issue by hydrated** [segmentio/analytics-android#417]
I am using cradle to migrate library like this 
{
	compile 'com.segment.analytics.android:analytics:4.+'
}

And it works fine before until today while I am rebuilding my project, the app starts crash in any call of this without changing any code of my project.

Analytics.with(MainFragmentActivity.this).track("Clicked Feedback");

Here is the crash log

E/AndroidRuntime(28709): 	at com.segment.analytics.IntegrationOperation$10.run(IntegrationOperation.java:189)
E/AndroidRuntime(28709): 	at com.segment.analytics.Analytics.performRun(Analytics.java:1025)
E/AndroidRuntime(28709): 	at com.segment.analytics.Analytics$4$1.run(Analytics.java:258)
E/AndroidRuntime(28709): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(28709): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(28709): 	at android.os.Looper.loop(Looper.java:211)
E/AndroidRuntime(28709): 	at android.app.ActivityThread.main(ActivityThread.java:5389)
E/AndroidRuntime(28709): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28709): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(28709): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
E/AndroidRuntime(28709): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by hydrated** [comment]
I did some test. v4.0.6 crashes but v4.0.5 doesn't.

**Comment by f2prateek** [comment]
Fixed on 4.0.7
