### ISSUE TITLE
.screen() documentation error?

### ISSUE THREAD

**Issue by rreusser** [segmentio/analytics-android#418]
The [`screen` documentation](https://segment.com/docs/libraries/android/#screen) has example:

```java
Analytics.with(context).screen("Photo Feed", new Properties().putValue("Feed Length", "26"));
```

[Valid type signatures](https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L415-L453) are:

```java
screen(String, String)
screen(String, String, Properties)
screen(String, String, Properties, Options)
```

Unless I'm mistaken (I am new to Java), does this make the example with one `String` invalid? Appears the correction would be:

```java
Analytics.with(context).screen("Photo Feed", null, new Properties().putValue("Feed Length", "26"));
```

**Comment by f2prateek** [comment]
That is correct, the docs are invalid

**Comment by f2prateek** [comment]
Updated docs https://segment.com/docs/libraries/android/#screen

**Comment by rreusser** [comment]
Awesome, thanks! :tada:
