### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by brendonboshell** [segmentio/analytics-android#420]
I would like to fork this project under the MIT license, which it claims to be distributed under. However, there seems to be many files that claim to be licensed under Apache License 2.0. Searching for 'Apache License' yields 10 instances of use, where copyright is assigned to "Prateek Srivastava", "Chris Banes" or "Square, Inc". I think it would be clearer to have all files under the same license.

**Comment by f2prateek** [comment]
We can't change the Chris Banes and Square ones, but I can change mine. I think it was just filled in by the IDE.
