### ISSUE TITLE
java.io.FileNotFoundException: https://api.segment.io/v1/import

### ISSUE THREAD

**Issue by pandey-adarsh147** [segmentio/analytics-android#430]
Payloads were rejected by server. Marked for removal.
                                                                com.segment.analytics.Client$UploadException: HTTP 400: Bad Request. Response: Could not read response body for rejected message: java.io.FileNotFoundException: https://api.segment.io/v1/import

I am keep getting this.

**Comment by f2prateek** [comment]
Do you have a reproducible case?

**Comment by f2prateek** [comment]
Closing since the SDK handles this gracefully, please re-open if you have a reproducible case and we can investigate the cause.
