### ISSUE TITLE
Opt-out for Android

### ISSUE THREAD

**Issue by cancan101** [segmentio/analytics-android#432]
The iOS library has ability to opt-in / out: https://segment.com/docs/libraries/ios/#opt-out but I don't see similar calls for the Android library.

I see this: https://github.com/segmentio/analytics-android/issues/8, but don't see the `optOut` methods in the code.

**Comment by f2prateek** [comment]
This is not supported in the Android library currently. For now best thing to do is add your own boolean check before calling analytics methods.
