### ISSUE TITLE
shouldUseLocationServices equivalent for Android

### ISSUE THREAD

**Issue by cancan101** [segmentio/analytics-android#433]
Is there an equivalent to [`shouldUseLocationServices`](https://segment.com/docs/libraries/ios/#location-services) for Android?

**Comment by f2prateek** [comment]
The Android library does not record location information by default, so no.

**Comment by cancan101** [comment]
Is there a way to get the android library to record location information?

**Comment by f2prateek** [comment]
No, you must track the location manually and attach it to context https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java#L250

**Comment by cancan101** [comment]
Any reason not to do that automatically like on ios?

**Comment by f2prateek** [comment]
Different apps need different levels of accuracy. Some are happy with the last known location and some will need to know about periodic updates.
