### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in ValueMap

### ISSUE THREAD

**Issue by abkaplan07** [segmentio/analytics-android#439]
Observed this error in our production app running Segment Analytics v4.0.4. User was trying to log into our app (therefore no Identify calls had been made yet).

Stack Trace:
java.lang.ArrayIndexOutOfBoundsException length=8; index=-913956946 
    HashMap.java:335 java.util.HashMap.containsKey
    ValueMap.java:71 com.segment.analytics.ValueMap.containsKey
    IntegrationOperation.java:174 com.segment.analytics.IntegrationOperation$10.run
    Analytics.java:1025 com.segment.analytics.Analytics.performRun
    Analytics.java:258 com.segment.analytics.Analytics$4$1.run
    Handler.java:800 android.os.Handler.handleCallback
    Handler.java:100 android.os.Handler.dispatchMessage
    Looper.java:194 android.os.Looper.loop
    ActivityThread.java:5415 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invokeNative
    Method.java:525 java.lang.reflect.Method.invoke
    ZygoteInit.java:833 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:600 com.android.internal.os.ZygoteInit.main
    NativeStart.java:-2 dalvik.system.NativeStart.main

Device:
Make/Model: Vivo Y20T (chinese model) 
OS: Android 4.2.2 (Jelly Bean)

**Comment by f2prateek** [comment]
Please update to the latest version.
