### ISSUE TITLE
Analytics.waitForAdvertisingId()  block UI-Thread 5s~15s

### ISSUE THREAD

**Issue by deltaguita** [segmentio/analytics-android#440]
Hi segmentio team:

I  found out  that method Analytics.waitForAdvertisingId (Analytics line : 412) always lock UI thread seconds when first tracking.

It's mean that we should put tracking in background thread?    

![screenshot_20160530-112436](https://cloud.githubusercontent.com/assets/3380016/15639248/fbcac938-265b-11e6-80d7-18e4e298684a.png)

Regards.

Wells 
wells@upn.com.tw

**Comment by f2prateek** [comment]
This has been fixed by https://github.com/segmentio/analytics-android/pull/435. It will be out in a release this week.

**Comment by deltaguita** [comment]
Hi:

May i know which day or older version can avoid this issue ？ 
I got some feedback from user for it.
