### ISSUE TITLE
Integration with JobScheduler/GcmNetworkMnaager/JobDispatcher

### ISSUE THREAD

**Issue by jensck** [segmentio/analytics-android#455]
I'm not seeing an easy way to control publishing batches of data via JobScheduler (et al).  It'd be really great to get some integration here.

**Comment by f2prateek** [comment]
We have to meet the lowest common denominator and unfortunately none of these options meet our requirements:
 
1. JobScheduler (only API 21+)
2. GcmNetworkManager (requires GCM dependency)
3. Job Dispatcher (requires firebase-job-dispatcher dependency)

Additionally I don't think there's significant value in adding support for this. Our SDK is minimal in terms of the networking it does, exposes a fair amount of configuration options (flush timer + flush size) and doesn't need any of the advanced exposed by these libraries. 

The flushing is completely transparent to you as a user and 100% handled by the library so I don't see any benefits of supporting these via additional APIs.

That being said, if you absolutely need to for whatever reason (let us know why!) you could always set the flush timer and size to something really large, and schedule your own job with whichever framework you're using and call `analytics.flush` in that job.

If you do go this route, let me know what sort of improvements you see and if it's significant we can consider releasing an extension module that does this (I didn't see any performance/battery/network usage improvements in my testing).
