### ISSUE TITLE
When will be update the latest version of Google Play Services?

### ISSUE THREAD

**Issue by pmbfish40** [segmentio/analytics-android#458]
I have integrated 
com.google.android.gms:play-services-base:9.0.2'
com.google.android.gms:play-services-gcm:9.0.2

when I am using the dependency

compile('com.segment.analytics.android:analytics-integration-google-analytics:+') {
        transitive = true
    }

I got this error

failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzpq.class

I know the solution:
You have to integrate the latest version of Google play services. What you can suggest here?

**Comment by f2prateek** [comment]
The correct repo to open this issue is https://github.com/segment-integrations/analytics-android-integration-google-analytics/issues
