### ISSUE TITLE
context.app.build should be a string

### ISSUE THREAD

**Issue by schmohlio** [segmentio/analytics-android#481]
The [app_build_key](https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java#L209) is added to the context as an integer, as opposed to a string. This differs from OS libraries, and the general representation of context app fields as a dictionary with string values (see [segment](https://segment.com/docs/spec/common/#structure))

This breaks compatibility with downstream applications. Could we align on a string type for this field?

**Comment by f2prateek** [comment]
`build` wasn't spec'd to be a string (even though the example shows a string), so we just used whatever types the platform had https://developer.android.com/reference/android/content/pm/PackageInfo.html#versionCode.

**Comment by f2prateek** [comment]
Changing it to a string now will have the effect of breaking applications who were depending on the field being a number. Might have to think through the transition, but for now it's best downstream applications handle both.

**Comment by schmohlio** [comment]
Ok, thanks @f2prateek. as an overall suggestion it would be helpful if these libraries had specs for the "meta" fields. On the segment website there is a clear suggestion to use the same types for common fields, especially since their schema is not sent with the message or implicit in the version.

**Comment by f2prateek** [comment]
Yup agreed, and we'll definitely fix this in the next major release, just in an awkward place currently because of a historical mistake.

**Comment by f2prateek** [comment]
Tracking internally in JIRA https://segment.atlassian.net/browse/LIB-122

**Comment by f2prateek** [comment]
This will be fixed in version 4.4.0-beta1 onwards - https://github.com/segmentio/analytics-android/pull/604
