### ISSUE TITLE
anonymousId should not be included in Traits.

### ISSUE THREAD

**Issue by NightlyNexus** [segmentio/analytics-android#510]
The iOS SDK does not have this behavior, and https://segment.com/docs/spec/identify/ does not seem to document this.
Might be a breaking change to consider for 5.0? Would you consider a PR?

**Comment by f2prateek** [comment]
Sorry missed this. Yes this was legacy behaviour, and I want to fix it. And it will be a breaking change unfortunately. Though you might be able to do this sooner than you think with interceptors! https://github.com/segmentio/analytics-android/tree/interceptors

**Comment by f2prateek** [comment]
Tracking internally in JIRA https://segment.atlassian.net/browse/LIB-121

**Comment by cem2ran** [comment]
@f2prateek has this issue been resolved?

**Comment by f2prateek** [comment]
hey @cem2ran not yet. We'll close the issue and link to the code that changes this when it's done.

**Comment by hitesh-banknovo** [comment]
I have also faced the same issue and waiting for the fix.

**Comment by jobowoo** [comment]
@f2prateek - do you have an update on this? I'm noticing that both `anonymousId` and `userId` are being set on the `identify` method. Thanks!

**Comment by prayansh** [comment]
Hi! as stated earlier, this will probably be a breaking change, so will likely be implemented in our 5.+ series. 

If you are currently affected by this, you can use `Middlewares` as a workaround. Here is a snippet that will remove the `anonymousId` from the traits object for an identify event.
```java
new Middleware() {
  @Override
  // This middleware removes the anonymousId key-value from traits
  public void intercept(Chain chain) {
    BasePayload payload = chain.payload();
    if (chain.payload().type() == BasePayload.Type.identify
        && chain.payload().containsKey("traits")
        && chain.payload().getValueMap("traits").containsKey("anonymousId")) {
      ValueMap traits = chain.payload().getValueMap("traits");
      ValueMap copyTraits = new ValueMap();
      copyTraits.putAll(traits);
      copyTraits.remove("anonymousId");
      payload.put("traits", copyTraits);
    }
    chain.proceed(payload);
  }
}
```
