### ISSUE TITLE
(Question) Regarding Play Services requirement

### ISSUE THREAD

**Issue by greyvugrin** [segmentio/analytics-android#526]
We have an an IOT/Robotics device (not a phone / mobile) running Android, which does not have Play services on it.

Per your documentation, the Android SDK has a reference to it to get the context.device.advertisingId.

Adding Play Services is not an option for us, and we were wondering if there is a way around this (like setting the advertisingId ourselves somewhere).

**Comment by f2prateek** [comment]
You could set a custom Map for the "device" key which would have your advertising ID https://segment.com/docs/sources/mobile/android/#context. That being said, a lot of tools rely on this on specifically being the Google Advertising ID (which as I understand is only available via Play Services), so I would advise against it, and maybe send it as a custom property instead.
