### ISSUE TITLE
OkHttpClient Leak

### ISSUE THREAD

**Issue by caipivara** [segmentio/analytics-android#554]
Library version: 4.3.0

Every time I run it I see on logs:

```
W/OkHttpClient: A connection to https://api.segment.io/ was leaked. Did you forget to close a response body?
```

**Comment by f2prateek** [comment]
Hi, I'm not seeing this our sample app.  Could you describe the steps to reproduce this? Which version of Android etc. Would be helpful as well.

**Comment by eygraber** [comment]
I'm seeing this in library version 4.3.1 using a Pixel running 8.1

**Comment by mpierucci** [comment]
@f2prateek Im also seeing this warners. 
Library versión 4.3.1
Device LGE Nexus 5X API 26 (but happens on other devices as well)
As per reproduce set up some screen analítica and navigate through the app a little bit.

**Comment by ArthurSav** [comment]
Why is this closed?

Library version 4.3.1 using a Samsung Galaxy S+ running Android 8.0.
Implemented some simple events + screen names for the first time today and i'm seeing this error.

As for reproducing the issue i suggest doing the same as mentioned above

> try setting up some screen analytics and navigate through the app a little bit.

**Comment by f2prateek** [comment]
> try setting up some screen analytics and navigate through the app a little bit.

We did, and we haven't been able to reproduce the error you are describing on an emulator, Genymotion virtual device and a physical Pixel device.

**Comment by ArthurSav** [comment]
I'll see if i can reproduce the issue reliably and maybe provide some insight about the cause.
In the meantime [this thread](https://github.com/square/okhttp/issues/2311) describes the issue and a potential solution. Seems that a HTTP connection is opened but not closed in all scenarios(i.e closes only for requests returning code 200)

**Comment by f2prateek** [comment]
I don't think that's the root cause. The code for this is here https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/SegmentIntegration.java#L374. It's called in the finally which should ensure that the connection is always closed.

**Comment by kassim** [comment]
I'm getting this in my app too.
Anyone figured the fix?

**Comment by panzhiev** [comment]
The same problem occurred.
`W/OkHttpClient: A connection to https://api.segment.io/ was leaked. Did you forget to close a response body?`
Does anyone have a solution?
