### ISSUE TITLE
Array out of bounds exception 

### ISSUE THREAD

**Issue by bkparse** [segmentio/analytics-android#560]
Using segment 4.3.0 notice this issue was set to fixed but still experiencing it 
eg) https://github.com/segmentio/analytics-android/issues/441

`12-19 13:27:11.669 22860 23038 E AndroidRuntime: FATAL EXCEPTION: Segment-SegmentDispatcher
12-19 13:27:11.669 22860 23038 E AndroidRuntime: Process: com.example.ts, PID: 22860
12-19 13:27:11.669 22860 23038 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-1628602933
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at java.util.Arrays.checkOffsetAndCount(Arrays.java:4857)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at libcore.io.IoBridge.read(IoBridge.java:466)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at java.io.RandomAccessFile.readBytes(RandomAccessFile.java:325)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at java.io.RandomAccessFile.read(RandomAccessFile.java:354)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:413)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at com.segment.analytics.QueueFile.ringRead(QueueFile.java:261)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at com.segment.analytics.QueueFile.readElement(QueueFile.java:176)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at com.segment.analytics.QueueFile.forEach(QueueFile.java:422)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at com.segment.analytics.QueueFile.toString(QueueFile.java:552)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at com.segment.analytics.SegmentIntegration.performEnqueue(SegmentIntegration.java:218)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:430)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-19 13:27:11.669 22860 23038 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by f2prateek** [comment]
Doesn't look like you're using 4.3.0.

> com.segment.analytics.SegmentIntegration.performEnqueue(SegmentIntegration.java:218) 12-19 13:27:11.669 22860 23038 E AndroidRuntime:

That points to https://github.com/segmentio/analytics-android/blob/bffff1c18037c52dae3a652b24ffd6b2ce49d848/analytics/src/main/java/com/segment/analytics/SegmentIntegration.java#L209-L218

Could you share the exact setup you have as a PR against the sample app here https://github.com/segmentio/analytics-android/tree/master/analytics-samples/analytics-sample/src/main/java/com/segment/analytics/sample so we can reproduce better?

**Comment by bkparse** [comment]
i am using `compile 'com.segment.analytics.android:analytics:4.3.0'` in gradle will make a pr

**Comment by bkparse** [comment]
Ops it was the wrong branch sorry
