### ISSUE TITLE
Attempt to invoke virtual method 'com.segment.analytics.ValueMap com.segment.analytics.ProjectSettings.integrations()' on a null object reference

### ISSUE THREAD

**Issue by chuyeoh** [segmentio/analytics-android#592]
### Analytics version
`com.segment.analytics.android:analytics:4.3.1'`

Crashes has been logged for a while now (6 months) on our app in production. We have placed breadcrumbs to help identify the cause of this crash however, we are unable to reproduce this crash.

Our breadcrumbs tells us that this happens during app start up on a no network conditions. 

During our startup process we initialise Analytics and identify our users.

### App identify process
```
public void identify(@Nullable String userId, @Nullable ReadableMap properties) {
        Traits traits = new Traits();

        if (properties != null) {
            traits.putAll(properties.toHashMap());
        }

        Analytics.with(getReactApplicationContext()).identify(userId, traits, null);
    }
```

### Raw error
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.segment.analytics.ValueMap com.segment.analytics.ProjectSettings.integrations()' on a null object reference
    at com.segment.analytics.Analytics.performInitializeIntegrations(Analytics.java:1000)
    at com.segment.analytics.Analytics$2$1.run(Analytics.java:201)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6134)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by f2prateek** [comment]
Weird. I was thinking we should add a guard, but it looks like we already have one here - https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L256.

**Comment by billgockeler** [comment]
We are experiencing this issue as well. Have there been any updates on this?

**Comment by kpl-goel** [comment]
@f2prateek we are experiencing the same issue. 

Here is my theory https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L256 in this line you check if project settings are null or empty. But you don't check explicitly for integration settings are null or empty. And when initialization is performed, it looks for integration settings from project settings which could be null.

This scenario is valid in cases where server request is successful but integrations are not returned in the response. In my opinion we should do explicit check for null or empty check after this line as well https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L1411 for integration settings.

**Comment by bsneed** [comment]
Thanks again for the PR @billgockeler!  This change will show up in the next beta release.
