### ISSUE TITLE
SharedPreference problem with Application Installed event

### ISSUE THREAD

**Issue by sergiovelorio** [segmentio/analytics-android#596]
Hello guys.

We found a small bug concerning the Application Installed event getting sent multiple times while opening the app several minutes after the install.
This happens every time the apps gets opened after closing it.

I debugged and found that the previousBuild value remains -1, meaning this code is not being processed properly:

SharedPreferences.Editor editor = sharedPreferences.edit();
    editor.putString(VERSION_KEY, currentVersion);
    editor.putInt(BUILD_KEY, currentBuild);
    editor.apply();

Thats in Analytics.java:417

Hope it gets fixed soon.
Cheers!

**Comment by f2prateek** [comment]
Hi - the code looks reasonable to me https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L415-L420.

Can you check what your `currentBuild` https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L384 is?

**Comment by sergiovelorio** [comment]
Good morning.
According to the documentation, im including the library this way:

implementation 'com.segment.analytics.android:analytics:4.+'

Therefor, the code sends this:

![image](https://user-images.githubusercontent.com/4750841/47569909-12915600-d8f2-11e8-8907-918503cb90be.png)

Which is my app version code and version number.
I have a login process in my app and this happens when I login in another device. 
Seems weird to me, also Im not deleting cache nor sharepreferences directly.

**Comment by prayansh** [comment]
Closing this issue, please reopen if faced again (hopefully with more context/details)
