### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by sigma18** [segmentio/analytics-android#597]
E/Analytics: Payloads were rejected by server. Marked for removal.
    com.segment.analytics.Client$HTTPException: HTTP 400: Bad Request. Response: Bad Request
        at com.segment.analytics.Client$1.close(Client.java:66)
        at com.segment.analytics.SegmentIntegration.performFlush(SegmentIntegration.java:355)
        at com.segment.analytics.SegmentIntegration$3.run(SegmentIntegration.java:319)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:544)

**Comment by f2prateek** [comment]
Do you have any steps for us to reproduce this, or more error details (e.g. by checking the raw http request)?

**Comment by sigma18** [comment]
In Charles Contents :

{
	"batch": [, , , , , ],
	"sentAt": "2018-11-08T04:47:46.352Z"
}

or

{
	"batch": [, ],
	"sentAt": "2018-11-08T04:47:45.722Z"
}

{
	"batch": [, , ],
	"sentAt": "2018-11-08T04:46:21.198Z"
}

**Comment by f2prateek** [comment]
Interesting. Maybe we need to add a check to guard against empty payloads here https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/SegmentIntegration.java#L483.

It's unclear why this is happening in the first place though, so would be good to understand the root cause first.

**Comment by sigma18** [comment]
Not just empty, also invalid json appears

{"batch":[{"channel":"mobile","type":"track","messageId":"05539173-9dd8-4d55-a2cc-4a0163419c2c","timestamp":"2018-11-08T11:57:54.929Z","context":{"app":{"build":0,"name":"Hayalami","namespace":"com.xayalami.hayalami","version":"102.2.10"},"traits":{"_contentCountryId":4,"_device_available":"5680.211","_pushEnabled":true,"_email":"aaa@qq.com","_ipCountryId":"1","_facebookConnected":false,"_contentCountry":"US","_user_type":0,"_nickname":"sigma","_ipCountry":"CN","_autoDownloadOpen_OnChannelNumber":0,"_emailConnected":true,"email":"aaa@qq.com","_localeLanguage":"zh","anonymousId":"d24ede90-cfc1-4955-bda5-3cca18a1a3e4","_device_usage_auto_download":"0.0","_autoDownloadOpen":false,"_net-mode":"wifi","userId":"324620","_timeZoneConverted":8,"_deviceId":"ffffffff-80ac-39bb-0000-0000003652ee","_loginFrom":"email","_localeCountry":"CN","_device_usage_download":"0.0"},"library":{"name":"analytics-android","version":"4.3.1"},"os":{"name":"Android","version":"5.1.1"},"timezone":"Asia/Shanghai","screen":{"density":2.0,"width":720,"height":1280},"userAgent":"Dalvik/2.1.0 (Linux; U; Android 5.1.1; ASUS_X013DB Build/LMY47V)","locale":"zh-CN","device":{"id":"80dd6a3d0c2ebcee","manufacturer":"asus","model":"ASUS_X013DB","name":"ASUS_X013D_1","advertisingId":"2c74e039-bee2-4991-a2c7-f65fb375d31c","adTrackingEnabled":true},"network":{"wifi":true,"carrier":"","bluetooth":false,"cellular":false}},"integrations":{"AppsFlyer":false},"userId":"324620","anonymousId":"d24ede90-cfc1-4955-bda5-3cca18a1a3e4","event":"Swipe","properties":{"appName":"intl-event","channel_following":"true","contentCountry":"US","contentCountryId":4,"direction":"right","episode_download":"false","episode_id":"13944002","episode_listen_later":"false","episode_progress":"0.0","event":"Swipe","id":"31","item_position":"24","net-mode":"wifi","push_channel":null,"push_id":null,"push_type":null,"screen_id":"13944001","screen_type":"episode:full","session_id":"9112fad3-7475-4190-8315-2b35d77cb53a","user_id":"324620","ts":1541678274909}}	{"channel":",{"channel":"mobile","type":"track","messageId":"c5060eeb-451c-4252-802b-a9a6f3ef4718","timestamp":"2018-11-08T11:57:55.096Z","context":{"app":{"build":0,"name":"Hayalami","namespace":"com.xayalami.hayalami","version":"102.2.10"},"traits":{"_device_available":"5678.121","_contentCountryId":4,"_pushEnabled":true,"_email":"aaa@qq.com","_ipCountryId":"1","_facebookConnected":false,"_contentCountry":"US","_user_type":0,"_nickname":"sigma","_ipCountry":"CN","_autoDownloadOpen_OnChannelNumber":0,"_emailConnected":true,"email":"aaa@qq.com","_localeLanguage":"zh","anonymousId":"d24ede90-cfc1-4955-bda5-3cca18a1a3e4","_device_usage_auto_download":"0.0","_autoDownloadOpen":false,"_net-mode":"wifi","userId":"324620","_timeZoneConverted":8,"_deviceId":"ffffffff-80ac-39bb-0000-0000003652ee","_loginFrom":"email","_localeCountry":"CN","_device_usage_download":"0.0"},"library":{"name":"analytics-android","version":"4.3.1"},"os":{"name":"Android","version":"5.1.1"},"timezone":"Asia/Shanghai","screen":{"density":2.0,"width":720,"height":1280},"userAgent":"Dalvik/2.1.0 (Linux; U; Android 5.1.1; ASUS_X013DB Build/LMY47V)","locale":"zh-CN","device":{"id":"80dd6a3d0c2ebcee","manufacturer":"asus","model":"ASUS_X013DB","name":"ASUS_X013D_1","advertisingId":"2c74e039-bee2-4991-a2c7-f65fb375d31c","adTrackingEnabled":true},"network":{"wifi":true,"carrier":"","bluetooth":false,"cellular":false}},"integrations":{"AppsFlyer":false},"userId":"324620","anonymousId":"d24ede90-cfc1-4955-bda5-3cca18a1a3e4","event":"Performance","properties":{"appName":"intl-event","channel_id":"106331","contentCountry":"US","contentCountryId":4,"current_position":"0","episode_duration":"1052407","episode_id":"13944003","event":"Performance","id":"8","net-mode":"wifi","push_channel":null,"push_id":null,"push_type":null,"section_type":"play prepared","session_id":"a20abfa0-eb27-4690-a100-eab9a524daf4","user_id":"324620","ts":1541678275067}}],"sentAt":"2018-11-08T11:57:55.904Z"}

**Comment by sigma18** [comment]
It seems to have something to do with multiple processes, we init segment and track event in two processes

**Comment by f2prateek** [comment]
Oh I see. The library is not designed to work with multiple processes.

As a workaround you can set a `tag` for each process https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L1181-L1194.

**Comment by SunilGoCars** [comment]
@sigma18 We are also facing same issue. Could you please tell how did you solve it?
