### ISSUE TITLE
Track offline events reliability

### ISSUE THREAD

**Issue by chuyeoh** [segmentio/analytics-android#609]
Our app is commonly used in a low network environment and most events track is done when the device is offline.

We have noticed that there are times when an event is not successfully tracked.
Do you know under what circumstances will the offline tracked event is lost?

We suspect that tracked events were lost when the app crashes before going online.
Will you be able to confirm this behaviour?

**Comment by TeresaNesteby** [comment]
hi @chuyeoh! Thanks for reaching out! For support questions, please reach out to our team directly at https://segment.com/contact/.
