### ISSUE TITLE
AppsFlyer instance initialized too late in AppsFlyer-Segment-Integration?

### ISSUE THREAD

**Issue by mlazari** [segmentio/analytics-android#610]
We use [AppsFlyer-Segment-Integration](https://github.com/AppsFlyerSDK/AppsFlyer-Segment-Integration) in our app and we're trying to get link data using `AppsflyerIntegration.ConversionListenerDisplay` as per [docs](https://github.com/AppsFlyerSDK/AppsFlyer-Segment-Integration#get-conversion-data) for performing deeplink navigation. The problem is that it's only called when the app is already open in background when the link is clicked. If the app is closed when the link is clicked, then the app opens, but `display` function is not called with link data. Regarding this issue I have 2 questions:

1. Is it possible that this happens because AppsFlyer instance is initialized too late from AppsFlyer-Segment-Integration? [AppsFlyer docs](https://support.appsflyer.com/hc/en-us/articles/207032126-AppsFlyer-SDK-Integration-Android#3-sdk-initialization) say that `startTracking` should be called either from `onCreate` in `Application` class or from `onCreate` in `Activity` class. I turned on logs with `.logLevel(Analytics.LogLevel.VERBOSE)` and it looks like `startTracking` is called after both `onCreate` methods are already executed.

2. Can we do something to fix this?

**Comment by mlazari** [comment]
I'm not sure if this is the right place for this issue, but https://github.com/AppsFlyerSDK/AppsFlyer-Segment-Integration repo seems to be not open for issues.

**Comment by TeresaNesteby** [comment]
Hi @mlazari  - Thanks for reaching out! For support questions, please reach out to our team directly at https://segment.com/contact/.
