### ISSUE TITLE
Does DeepLinkDispatch uses Branch IO SDK?

### ISSUE THREAD

**Issue by IordacheClaudiu** [segmentio/analytics-android#613]
Hi,
We have an issue on Google Play Store with our app and I was wondering if you're using `Branch IO SDK` or calling  `https://api.branch.io/v1/applist`?
Thanks.

**Comment by f2prateek** [comment]
The core library doesn't do anything here https://github.com/segmentio/analytics-android/search?utf8=✓&q=branch&type=. 

It might be that you are using the Branch SDK?

I would suggest reaching out to our [support team](https://segment.com/contact/) so they can help you debug this further.
