### ISSUE TITLE
SSL Certificate Pinning support

### ISSUE THREAD

**Issue by sergiomarqmoura** [segmentio/analytics-android#614]
Hello!
Any plans on adding [certificate pinning](https://medium.com/@appmattus/android-security-ssl-pinning-1db8acb6621e) support to the SDK?

**Comment by f2prateek** [comment]
There isn't any plan to do so currently, and more generally folks are moving away from it (e.g. Google Chrome https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ and https://www.theregister.co.uk/2017/10/30/google_hpkp/).

We do offer an [API](https://github.com/segmentio/analytics-android/blob/93c7d5bb09b593440a2347a6089db3e9f74012da/analytics/src/main/java/com/segment/analytics/ConnectionFactory.java) to hook into how the library makes network requests (example: https://segment.com/docs/sources/mobile/android/#proxy-http-calls), which could be used to implement SSL pinning if you desire. I would advise against this however, as we change certificates on our API roughly every year or two and don't announce these ahead of time, so you will run into the case where we've updated certificates, and you haven't updated the chain bundled in your application (and even if you have, your users might be on old versions).

If you would like to see this more officially supported, I would suggest reaching out to our [support team](https://segment.com/contact/) to file a feature request and stay up to date on the progress
