### ISSUE TITLE
Crash when recording screen views

### ISSUE THREAD

**Issue by curtinmartis** [segmentio/analytics-android#615]
This issue came through Fabric in our production app running version 4.3.1 of the Segment SDK. It looks like the PackageManager died at some point while the SDK was collecting information to record our screen using the automatic screen recording.

Here's the [Stacktrace](https://github.com/segmentio/analytics-android/files/3112627/com.transloc.microtransit_issue_crash_5CBFD536003B00011F338499AC697E82_DNE_0_v2.txt). I have no idea how to reproduce it, but let me know if there's something I can do to help diagnose the issue.

**Comment by f2prateek** [comment]
This seems hard to reproduce. What's interesting is that we actually call the package manager in other places too (e.g. https://github.com/segmentio/analytics-android/blob/93c7d5bb09b593440a2347a6089db3e9f74012da/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java#L205), so I would expect those to cause a crash too. This isn't a checked exception, and the package manager docs also don't provide any guidelines on what do in this case (https://developer.android.com/reference/android/content/pm/PackageManager). I've added this to our [internal JIRA](https://segment.atlassian.net/browse/LIB-1169), I would suggest reaching out to our support team so they can keep you updated with the progress.
