### ISSUE TITLE
Recommended Proguard configuration

### ISSUE THREAD

**Issue by lordcodes** [segmentio/analytics-android#617]
In your documentation for the Segment Android library you say that the required Proguard configuration is to keep all Segment package classes.

I hadn't seen this when developing a new Android app and have been using Segment in release mode (with R8 shrinking enabled) without any Proguard configuration with no issues. I am using the MixPanel integration.

I had read you used reflection for the integrations, however, I can't see this in the code that connects the integrations and so far am seeing Segment Analytics and MixPanel analytics via it working perfectly fine with R8 shrinking and obfuscation enabled.

I am wondering therefore if the recommended Proguard configuration is actually needed anymore? Or if it is, what I am missing?

**Comment by f2prateek** [comment]
I don't think you should need a custom proguard configuration anymore for the core library. However, you might still need configurations specific to integrations, e.g. the [WebEngage SDK](https://segment.com/docs/destinations/webengage/) needs the following proguard configuration (with or without Segment):

```
 -keep class com.webengage.sdk.android.**{*;}
-dontwarn com.webengage.sdk.android.**
```

**Comment by lordcodes** [comment]
Thank you for clearing that up.
