### ISSUE TITLE
Alias: not seeing NewTestingUser

### ISSUE THREAD

**Issue by markli** [segmentio/analytics-android#633]
after sent the newId by alias(NewTestingUser), from the console it is: 

analytics.alias("TestingUser", "TestingUser");

**Comment by aliasunder** [comment]
We're also having this problem.

We are using the `react-native-analytics` package and are having this issue issue only with Android, which uses this package. 

When aliasing a user with their new id, the Segment Debugger shows the previous Id passed in twice.

Example:
Previous Id: 39afb4b1-1225-44b9-89e4-3d124dd035eb
New Id: 89a110e6-f27f-4c10-b95a-0b0dba8a0778 

When calling `analytics.alias('89a110e6-f27f-4c10-b95a-0b0dba8a0778 ')` in our code, the Segment Debugger shows that Segment received the following input:

`analytics.alias("39afb4b1-1225-44b9-89e4-3d124dd035eb", "39afb4b1-1225-44b9-89e4-3d124dd035eb");`

I dug into this further and my logs show that the react-native-analytics package is passing the correct values, however `analytics-android` is where things break down. 

Another issue I noticed is that the payload includes an integration that should not be there, as it was not defined in the options.

` "integrations": {
    "library": {
      "name": "analytics-react-native",
      "version": "1.1.0-beta.1"
    }
  }`

I appreciate any input!

**Comment by prayansh** [comment]
@aliasunder and @markli #666 should fix this for you. Thanks for reporting
