### ISSUE TITLE
Reset calls are inflating "Application Installed" events

### ISSUE THREAD

**Issue by richardmuttett** [segmentio/analytics-android#650]
```
/**
 * Resets the analytics client by clearing any stored information about the user. Events queued on
 * disk are not cleared, and will be uploaded at a later time.
 */
public void reset() {
  Utils.getSegmentSharedPreferences(application, tag).edit().clear().apply();
  traitsCache.delete();
  traitsCache.set(Traits.create());
  analyticsContext.setTraits(traitsCache.get());
  runOnMainThread(IntegrationOperation.RESET);
}
```
The documentation indicates that we should call `reset()` when logging out a user as it "Resets the analytics client by clearing any stored information about the user."
However, that method includes a call to `Utils.getSegmentSharedPreferences(application, tag).edit().clear().apply()` which is therefore seemingly resetting all data, not just user data.

We believe that this is causing the `trackApplicationLifecycleEvents()` method to not see there is a previously recorded version and that results in false "Application Installed" events.

**Comment by bsneed** [comment]
@richardmuttett this looks to have been fixed in the 4.5 release.  Please reopen if the issue persists.
