### ISSUE TITLE
Device information is lost when using a Middleware

### ISSUE THREAD

**Issue by vinicius-animo** [segmentio/analytics-android#654]
Hi,

When using a Middleware to append data to `Device` (setting `token` to be more precise), the default device values - such as manufacturer, model - are lost.
The implementation was based on the official segment documentation about middlewares, which can be [found here](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/#middlewares).

This is the piece of code inside the middleware that overrides context fields:
```java
        BasePayload payload = chain.payload();
              Map<String, Object> originalContext = new LinkedHashMap<>(payload.context());
              Map<String, Object> mergedContext = Utils.deepMerge(
                originalContext,
                appendToContextMiddleware // we inject values here
              );

              BasePayload newPayload = payload.toBuilder()
                .context(mergedContext)
                .build();
```

When the context is not manipulated, we get:
```json
"device": {
    "adTrackingEnabled": true,
    "advertisingId": "5F8DFEA2-XXXX-XXXX-XXXX-DC0AF85335F7",
    "id": "B2D8C773-XXXX-XXXX-XXXX-D7EDEE88D607",
    "manufacturer": "Apple",
    "model": "iPad8,3",
    "type": "ios"
},
```

And after the context is set:
```json
"device": {
    "token": "something",
    "type": "ios"
},
```

Is there a way to ensure the default Device fields are added when manually setting device tokens in a middleware?
The entire implementation of this logic can be found here in the un-official [flutter_segment plugin](https://github.com/claimsforce-gmbh/flutter-segment/blob/master/android/src/main/java/com/example/flutter_segment/FlutterSegmentPlugin.java).

Thanks.

**Comment by prayansh** [comment]
Hi! @vinicius-animo. I tried reproducing the issue, but was unable to do so.
I copied over the `middleware` and `deepMerge` code to see the results but was able to see the correctly merged context object.
Here is the diff of the changes that i applied https://github.com/segmentio/analytics-android/commit/e2dfb1e7e44f061bc2a3c928741ed843f86ca621 and i have attached a shortened version of the json payloads that i see in the segment debugger. 

Without middleware executing 
```
{
  ...
  "context": {
    "app": {
      ...
    },
    "device": {
      "adTrackingEnabled": true,
      "advertisingId": "509fe3c5-fc36-472c-836f-964aff9894f0",
      "id": "17a8dcff85fe4df1",
      "manufacturer": "Google",
      "model": "Android SDK built for x86",
      "name": "generic_x86",
      "type": "android"
    },
    ...
  }
}
```
With middleware executing
```
{
  ...
  "context": {
    "app": {
      ...
    },
    "device": {
      "adTrackingEnabled": true,
      "advertisingId": "509fe3c5-fc36-472c-836f-964aff9894f0",
      "id": "17a8dcff85fe4df1",
      "key": "value",
      "manufacturer": "Google",
      "model": "Android SDK built for x86",
      "name": "generic_x86",
      "type": "android"
    },
    ...
  }
}
```

I am not sure as to what went wrong with ur implementation, but if u can provide us with more details, we would be happy to look into it

**Comment by MaiKaY** [comment]
Hi @prayansh,
maybe it was fixed with the latest version. We are using version `4.5.0-beta.0` where this merge problem happens.

We will upgrade to the latest version and double check it again.

**Comment by prayansh** [comment]
Sounds good. Closing this issue for now. Please reopen if it doesnt work out for you.
