### ISSUE TITLE
using trackDeepLinks() Validate if the intent has data to avoid an NPE

### ISSUE THREAD

**Issue by pjcyber** [segmentio/analytics-android#657]
The SDK is assuming if the activity has an intent it must have an URL associated. with is a wrong assumption considering activities can be launched using intent for simple data.

https://github.com/segmentio/analytics-android/blob/a9fefda981bd67e4b151f1e466e3113fdb866f00/analytics/src/main/java/com/segment/analytics/AnalyticsActivityLifecycleCallbacks.java#L101

**Comment by prayansh** [comment]
@pjcyber #663 should fix this issue. Thanks for reporting
