### ISSUE TITLE
DeadSystemException!!! This is a common Exception among users.NEED FIX...

### ISSUE THREAD

**Issue by marktian1** [segmentio/analytics-android#661]
java.lang.RuntimeException:android.os.DeadSystemException
--
2 android.app.ContextImpl.checkPermission(ContextImpl.java:1533)
3 ......
4 Caused by:
5 android.os.DeadSystemException:
6 android.app.ContextImpl.checkPermission(ContextImpl.java:1533)
7 android.app.ContextImpl.checkCallingOrSelfPermission(ContextImpl.java:1571)
8 android.content.ContextWrapper.checkCallingOrSelfPermission(ContextWrapper.java:685)
9 com.segment.analytics.internal.Utils.hasPermission(Utils.java:140)
10 com.segment.analytics.internal.Utils.isConnected(Utils.java:303)
11 com.segment.analytics.SegmentIntegration.shouldFlush(SegmentIntegration.java:326)
12 com.segment.analytics.SegmentIntegration.submitFlush(SegmentIntegration.java:310)
13 com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:509)
14 android.os.Handler.dispatchMessage(Handler.java:102)
15 android.os.Looper.loop(Looper.java:154)
16 android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by bsneed** [comment]
This isn't really enough information here to do anything with.  Please reopen if you can provide a more detailed issue report w/ reproduction steps, some context of what's happening, etc.
