### ISSUE TITLE
Publish aar correctly

### ISSUE THREAD

**Issue by Sloy** [segmentio/analytics-android#696]
We updated our Segment dependency to the 4.8.0 version, which includes the fix for https://github.com/segmentio/analytics-android/pull/668. However, it's not working. We just realized that the Segment dependency imports the `jar` file (java only) instead of the `aar` file (java + android) which includes the Proguard configuration.

Apparently there's some issue with the maven publication, and it's not generating the `pom.xml` file correctly. It's missing the `<packaging>aar</packaging>` declaration.
For comparison, [here is the Segment SDK pom.xml](https://repo1.maven.org/maven2/com/segment/analytics/android/analytics/4.8.2/analytics-4.8.2.pom), and [here is another one](https://repo1.maven.org/maven2/com/appboy/appboy-segment-integration/5.0.0/appboy-segment-integration-5.0.0.pom) with the proper configuration.

We believe this could be fixed by updating the publishing Gradle configuration. Right now Segment is using the old deprecated `maven` plugin. (See https://github.com/segmentio/analytics-android/blob/master/gradle/gradle-mvn-push.gradle#L17). The Android Gradle Plugin now officially supports the new `maven-publish` plugin. More info in https://developer.android.com/studio/build/maven-publish-plugin

As a workaround, we tried to import the SDK dependency as `implementation("com.segment.analytics.android:analytics:4.8.2@aar")`, but this causes errors with other transitive dependencies, as Gradle thinks it's a completely different dependency. So right now we're back to adding the Proguard configuration in our own project.

**Comment by prayansh** [comment]
Hey @Sloy! Thanks for the info.  
> So right now we're back to adding the Proguard configuration in our own project.

Reading this, makes me think that you are not currently blocked. Is that right? Additionally, any reason why you think including the Proguard config in your own project is not an ideal solution?

**Comment by Sloy** [comment]
That's correct, we are not currently blocked by this. 

I don't think manually maintaining the Proguard config from third-party libraries in our projects is an ideal solution, is _a_ solution.

If we didn't have a mechanism for importing Proguard configurations from libraries, as it happened some years ago, that would be the only solution for sure. We would copy the Proguard configuration from the library readme, and make sure to check for any changes every time a new version is released, so we can _manually_ update the configuration. Or have people excluding everything in their app (as I've seen many times) because they don't have the time to deal with Proguard errors.

Now that we have an automated mechanism, I think it's on the best interest of everyone that the libraries takes care of the Proguard config, so consumers don't need to deal with the issues above. Just like we have transitive dependencies with maven/gradle so consumers don't need to maintain the dependencies from each library. I remember Android development before Gradle, and it wasn't pretty 😂. 

If the `aar` was working, the fix in https://github.com/segmentio/analytics-android/pull/668 would be available to everyone using this library. But instead, all of your clients must remember to manually configure Proguard. I'm sure you have a lot of clients. And I can tell you at Adevinta we have 4 projects using this library, and none of us remembered to include the Proguard configuration 😅.

Sorry, I got a bit philosophical there! I hope that was the answer you were looking for.

**Comment by prayansh** [comment]
Yup thats exactly what i was looking for. TYSM for the detailed explanation :). I don't want to make any promises about the timeline, since we are currently busy with other features/priorities and will have to punt this issue to sometime later. I have created an internal JIRA ticket so that it gets prioritized accordingly. 
I will make sure to tag you when a fix is ready :)

**Comment by Sloy** [comment]
Thank you @prayansh

**Comment by prayansh** [comment]
@Sloy i recently did some rework on our publication process, fixing the pom property issue. The newest version [`4.9.1-beta`](https://mvnrepository.com/artifact/com.segment.analytics.android/analytics/4.9.1-beta) is available if you want to try it out :)

**Comment by Sloy** [comment]
Hello @prayansh! Thank you a lot for getting back to me. The file list in Maven Repository looks promising :) 
I'll give it a try tomorrow and make sure the Proguard issue is finally solved with this change

**Comment by Sloy** [comment]
I couldn't break the `release` flavour of our app using this beta, so that's good! I expect it will work for all users in production when we publish a version with the updated SDK 😃 

Again, thanks for taking care of this! ❤️
