### ISSUE TITLE
App crashing after updating Segment to 4.7.1

### ISSUE THREAD

**Issue by AdamGrzybkowski** [segmentio/analytics-android#699]
Stacktrace 
```
Fatal Exception: java.lang.IllegalAccessError: Interface androidx.lifecycle.c implemented by class com.segment.analytics.AnalyticsActivityLifecycleCallbacks is inaccessible (declaration of 'com.segment.analytics.AnalyticsActivityLifecycleCallbacks' appears in base.apk)
       at com.segment.analytics.Analytics.<init>(Analytics.java:120)
       at com.segment.analytics.Analytics$Builder.build(Analytics.java:323)
       at io.example.android.segmentanalytics.di.SegmentAnalyticsModule$Companion.provideSegmentAnalytics$segmentanalytics_release(SegmentAnalyticsModule.java:2)
```

From what I could find it was introduced in this PR
https://github.com/segmentio/analytics-android/pull/667

Adding `-keep class androidx.lifecycle.DefaultLifecycleObserver` proguard rule fixes this problem

**Comment by bsneed** [comment]
cc @prayansh @migs647

**Comment by jimmy-jose** [comment]
Still having the issue in 4.9.0. 
please add this to documentation `-keep class androidx.lifecycle.DefaultLifecycleObserver` if this is not gonna be fixed. Lost a lot of time because of this.

**Comment by Hospes** [comment]
Same for me, was forced downgrade to 4.8.2 instead.
Will add `-keep class androidx.lifecycle.DefaultLifecycleObserver` to proguard and check if this gonna work

**Comment by prayansh** [comment]
Hi! Good callout, we will update our docs with the proguard config

**Comment by prayansh** [comment]
Here is the updated docs link! https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/android-faqs/#how-should-i-configure-proguard
