### ISSUE TITLE
Supporting 6 months offline

### ISSUE THREAD

**Issue by hatton** [segmentio/analytics-android#701]
Our non-profit reading app is used to support literacy education in developing countries, and the analytics are used to see which books are being read, and how well kids are doing on comprehension questions.  We use Segments warehouse service to populate our postgresql DB, then offer public dashboards showing how and where books are being read. So we love that this sdk saves 1000 events while waiting to send them when online. However, that is no longer enough.

In an upcoming aid project, 1400 tablets containing our app will go out to kids in a super rural part of the Pacific. Every six months, the tablets will be brought together for the purpose of getting new books and collecting analytics. The project needs our app to store up to six months of reading activity; at a minimum of 3 events per tiny book, some kids may blow past the 1000 events. Our event payloads are tiny.

#1 We are thinking of doing a fork that increases this to 10 * 10,000.   Do you see any red flags on that? If you'd rather we submit a PR that makes it configurable, we could do that instead.

#2 Even during the every-six-months gathering of the tablets, the project would still like to not depend on a rural connection to the internet. They would like to automatically pull the QueueFile off of every machine and store it for later processing. Does that sound feasible? In other words, are there any known barriers to us writing some utility that takes 1400 queue files, then sends each even to Segment, one at a time?

Thanks for your help!

**Comment by prayansh** [comment]
Hi! This is probably something we are not planning to support out of the box. If you still need this feature I would recommend forking the project (No red flags on forking it 😄 )

**Comment by hatton** [comment]
@prayansh OK, we'll do a fork. Any chance you could comment on this second need?

> #2 Even during the every-six-months gathering of the tablets, the project would still like to not depend on a rural connection to the internet. They would like to automatically pull the QueueFile off of every machine and store it for later processing. Does that sound feasible? In other words, are there any known barriers to us writing some utility that takes 1400 queue files, then sends each even to Segment, one at a time?

**Comment by prayansh** [comment]
i dont see a problem with that, although we do recommend you batch it up. Here are the docs for our [HTTP API](https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/). Hopefully that helps :)

**Comment by hatton** [comment]
Thank you @prayansh
