### ISSUE TITLE
Crash during Google Pre-launch report

### ISSUE THREAD

**Issue by cjpete** [segmentio/analytics-android#732]
Using Segment via `@segment/analytics-react-native` with `@segment/analytics-react-native-appsflyer`.

```
@segment/analytics-react-native@1.3.2
@segment/analytics-react-native-appsflyer@1.3.2
```

These appear to be dependent upon: `com.segment.analytics.android:analytics:4.9.0`

Detected on 4 devices in the pre-launch report:
* Samsung Galaxy S9 / Android 8.0 (SDK 26) / ARM64_V8
* Google Pixel 3 / Android 9 (SDK 28) / ARM64_V8
* Motorola moto e5 play / Android 8.1 (SDK 27) / ARM_V7
* Nokia Nokia 1 / Android 8.1 (SDK 27) / ARM_V7

```
FATAL EXCEPTION: main
Process: [com.bla.bla], PID: 27607
java.lang.AssertionError: Could not create instance of com.segment.analytics.p.
java.lang.NoSuchMethodException: <init> [interface java.util.Map]
	at com.segment.analytics.u.a(Unknown Source:58)
	at com.segment.analytics.u.a(Unknown Source:23)
	at com.segment.analytics.u.a(Unknown Source:4)
	at com.segment.analytics.w.h.e(Unknown Source:4)
	at com.segment.analytics.v.a.a.a.a(Unknown Source:4)
	at com.segment.analytics.i.a(Unknown Source:87)
	at com.segment.analytics.i$j$a.a(Unknown Source:72)
	at com.segment.analytics.l.a(Unknown Source:39)
	at com.segment.analytics.i.a(Unknown Source:6)
	at com.segment.analytics.i$j.a(Unknown Source:13)
	at com.segment.analytics.a.a(Unknown Source:40)
	at com.segment.analytics.a$a.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by prayansh** [comment]
Hi @cjpete as documented [here](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/android-faqs/#sts=How%20should%20I%20configure%20Proguard?) i would recommend adding this to your proguard file 
```
-keep class com.segment.analytics.** { *; }
```
to prevent any reflection classes from being obfuscated

**Comment by cjpete** [comment]
Thanks @prayansh, I'll see how this goes!

**Comment by cjpete** [comment]
@prayansh that fixed the issue, so thanks for pointing it out.

I'm a little confused though, as this wasn't a problem in our testing, but was in the google play installation. Would have been nice to catch this one earlier on. Do you know why this would be a difference when using, for example:

```
bundleStagingRelease <-- apk built for internal testing via appcenter (crash did not happen here)
assembleProductionRelease <-- aab built for google play internal testing (crash happened here)
```

Our build-types are configured to apply proguard mappings whenever it is a release variant:

```
    flavorDimensions "environment"
    productFlavors {
        staging {
            applicationIdSuffix ".staging"
            dimension "environment"
        }
        production {
            dimension "environment"
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
```

**Comment by cjpete** [comment]
> Hi @cjpete as documented [here](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/android-faqs/#sts=How%20should%20I%20configure%20Proguard?) i would recommend adding this to your proguard file
> 
> ```
> -keep class com.segment.analytics.** { *; }
> ```
> 
> to prevent any classes/methods from being obfuscated

I ended up adding the following:

```
# segment
-keep class com.segment.analytics.** { *; }
-keep class androidx.lifecycle.DefaultLifecycleObserver

# appsflyer
-keep public class com.android.installreferrer.** { *; }
```

**Comment by emartynov** [comment]
I just added #756
