### ISSUE TITLE
Release Crash 4.9.0: java.lang.IllegalAccessError Lifecycle

### ISSUE THREAD

**Issue by sanogueralorenzo** [segmentio/analytics-android#735]
Updated from 4.8.2 to 4.9.0

I'm seeing the following crash only on release builds (we have R8 enabled)

java.lang.IllegalAccessError: Interface androidx.lifecycle.e implemented by class com.segment.analytics.AnalyticsActivityLifecycleCallbacks is inaccessible (declaration of 'com.segment.analytics.AnalyticsActivityLifecycleCallbacks' appears in base.apk!classes2.dex) at com.segment.analytics.Analytics.<init>(SourceFile:28)
        at com.segment.analytics.Analytics$j.a(SourceFile:49)

Android SDK 29
Gradle version 6.7
AGP 4.1.1

Lifecycle version is 2.2.0 and hasn't been updated (so 4.8.2 with 2.2.0 works properly)

I've tried:
- Excluding lifecycle group from the dependency
- Force 2.2.0 strategy
- I've also tried reverting to 2.1.0 on lifecycle
- Adding the explicit dependency of lifecycle on the app level

None of the above worked. Suggestions?

**Comment by AraheemAYM** [comment]
I am also facing the same issue in release build when minifyEnabled=true
+1

**Comment by prayansh** [comment]
Does adding this to your Proguard config fix this issue? https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/android-faqs/#how-should-i-configure-proguard

**Comment by AraheemAYM** [comment]
Yes, It solves the problem.

Thanks

**Comment by sanogueralorenzo** [comment]
I will give it a try @prayansh would it be possible to add the above in the library's consumer proguard so clients don't have to add it?

**Comment by prayansh** [comment]
@sanogueralorenzo i will make sure to add it to our proguard config :)

**Comment by emartynov** [comment]
I just added #756
