### ISSUE TITLE
Crash - NoSuchMethodException relating to ScreenPayload and ValueMap

### ISSUE THREAD

**Issue by lordcodes** [segmentio/analytics-android#740]
After updating to version 4.9.0, we have been having crashes on a Samsung A5 due the Segment code ScreenPayload and ValueMap.

From our Crashlytics:

Fatal Exception: java.lang.AssertionError
  Could not create instance of k.l.a.e0. java.lang.NoSuchMethodException: <init> [interface java.util.Map]
    k.l.a.j0.e (ValueMap.java:9)
    k.l.a.l0.g.n (ScreenPayload.java:1)
    k.l.a.k0.a.a.a.f (MixpanelIntegration.java:3)
    k.l.a.y$a.a (IntegrationOperation.java:34)
    k.l.a.y.b (IntegrationOperation.java:8)
    k.l.a.b.e (Analytics.java:4)
    k.l.a.a.run (Analytics.java:1)

From looking into the Segment source code, I believe this starts in the Segment MixPanel integration which calls through to report an event using the ScreenPayload.properties which is an instance of `Properties`.
For some reason, the 'ValueMap' class uses reflection to create it, which seems to be failing in this situation and causing the whole app to crash.

**Comment by prayansh** [comment]
Hi! this seems like a problem related to proguard minification. Adding our [recommended proguard configuration]((https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/android-faqs/#sts=How%20should%20I%20configure%20Proguard?)) should fix this issue

**Comment by lordcodes** [comment]
@prayansh Why don't you include the proguard configuration within the SDK like other Android dependencies do? Since it was added via the consumer proguard files for libraries I don't have to add Proguard configuration for any other dependencies.

**Comment by emartynov** [comment]
@prayansh do you plan to add proguard rules to the library?

**Comment by emartynov** [comment]
I just created #756
