### ISSUE TITLE
Id field on Product should deserialize product_id instead of id?

### ISSUE THREAD

**Issue by Bucimis** [segmentio/analytics-android#746]
https://github.com/segmentio/analytics-react-native/issues/277 (mirrored https://github.com/Appboy/appboy-segment-android/issues/25)

We have an issue where a mutual customer is expecting to be able to pass `product_id` as the Id field on product objects, but only `id` is working. I believe it's because when deserializing `Product` objects, the Android code is expecting `id` instead of `product_id` https://github.com/segmentio/analytics-android/blob/006bd94aa4ed14ae3eaf9da508f2d0653d0be8c7/analytics/src/main/java/com/segment/analytics/Properties.java#L391 (which eventually flows down to our integration https://github.com/Appboy/appboy-segment-android/blob/master/appboy-segment-integration/src/main/java/com/segment/analytics/android/integrations/appboy/AppboyIntegration.java#L263)

Is that understanding correct? I think this may only really come up with react native type integrations, where things aren't typed by integrators using the Java objects before being passed into Segment.

**Comment by prayansh** [comment]
Yea this seems like an oversight, i have filed an internal Jira to map `id` and `product_id` to the same value. But until that change is shipped, i would recommend users to map both `id` and `product_id` (just like you recommended [here](https://github.com/Appboy/appboy-segment-android/issues/25#issuecomment-795839422)). I will post an update here once the change is shipped

**Comment by prayansh** [comment]
did not intend to close the issue 😓

**Comment by prayansh** [comment]
@Bucimis #761 should fix this issue. This change will be included in our next release
