### ISSUE TITLE
Id field on Product should support quantity

### ISSUE THREAD

**Issue by Bucimis** [segmentio/analytics-android#747]
From https://segment.com/docs/connections/spec/ecommerce/v2/ - ask from a mutual customer

**Comment by prayansh** [comment]
Hi @Bucimis even though we dont have an explicit mapping for `quantity` customers can easily set and retrieve it using the `ValueMap` APIs.
For example
```// put quantity
Product p = // some product;
p.put("quantity", 1); // put a quantity in
p.getInt("quantity", 0); // retrieve quantity
```
