### ISSUE TITLE
Crash on Android with IllegalArgumentException: INTERNET permission is required

### ISSUE THREAD

**Issue by kozyrevsergey89** [segmentio/analytics-android#748]
I can see `packageManager has died` line just before this crash happens in our crash reporting tool.
What I've found is that this sometimes happens when updating the app while talking to packageManager, and available fix it to repeat permission request at least once - this usually helps:
https://www.codota.com/web/assistant/code/rs/5c7cac8a2f7dae0001643522#L87
An example given from evernote android app.

**Comment by prayansh** [comment]
This should be resolved via #749
