### ISSUE TITLE
As consumer of library I want to have proguard rules bundled in the library

### ISSUE THREAD

**Issue by emartynov** [segmentio/analytics-android#756]
This will eliminate the need for the documentation and possible crashes for people that missed the proguard configuration part.

Simple explanation might be found https://proandroiddev.com/handling-proguard-as-library-developer-or-in-a-multi-module-android-application-2d738c37890

**Comment by emartynov** [comment]
Can we also discuss why such proguard rules are selected?

**Comment by prayansh** [comment]
Hi @emartynov! as of `analytics-android 4.9.1-beta.1+` the proguard configuration should be part of the distributable when fetched from maven. Please let us know if that doesnt work for you, and we can discuss further.

As to the question of our specific proguard rules: We internally use reflection to generate `Map`s for specific parameters, and when obfuscated using proguard these params/methods will throw a runtime exception. We have explored not using reflection, but didnt find a feasible alternative.

**Comment by emartynov** [comment]
Apologies, I should just check the source and find out that it is added 6 months ago. I see that the settings are different from the official [documentation](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/android-faqs/#how-should-i-configure-proguard). Do you want to update also documentation?

**Comment by prayansh** [comment]
good call! will make sure those get updated ASAP
