### ISSUE TITLE
Tracking timestamps are incorrect

### ISSUE THREAD

**Issue by oomathias** [segmentio/analytics-android#757]
**Issue introduced:** `4.8.0`

**Affects:** All users (i.e not device-specific)

**Reproduced on:** This can be reproduced across all devices as we are seeing this issue from users in the real world, however in my specific test case I've used a Galaxy A20e on Android 10.

### What's the issue?

We've noticed that the timestamps recorded by this library for tracking events can be incorrect by a margin of anywhere from a few minutes to several hours. In all cases, the timestamp reports that the event happened *earlier* than this actually occurs.

As we use segment tracking to help us understand user journeys and support them with issues, this has caused much confusion. The issue does not appear to be limited to any device or Android version and is likely affecting all Android users.

We use version `1.3.2` of the `analytics-react-native` package as part of our React Native app, which currently uses version `4.9.0` of this library. Based on our investigation, this bug was introduced in version `4.8.0`.

### What causes the issue?

The issue is caused by the use of `System.nanoTime()` inside the [NanoDate class](https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/internal/NanoDate.java#L48-L72) when creating event timestamps. This does not accurately calculate time offsets if the user has, for example, locked their phone in between using the app.

From the Android documentation ([link](https://developer.android.com/reference/android/os/SystemClock)):

> This clock stops when the system enters deep sleep (CPU off, display dark, device waiting for external input), but is not affected by clock scaling, idle, or other power saving mechanisms. This is the basis for most interval timing such as `Thread.sleep(millls)`, `Object.wait(millis)`, and `System.nanoTime()`.

Because the timer pauses when the user locks their device, this means that if the user subsequently returns to use the app, any new tracking event timestamps will be recorded as too early because it's not counting time that the phone spent idle.  For example, if a user is on the app, then locks their phone at 5:00pm for two minutes without killing the app, and then returns to use the app once more, all timestamps will be two minutes early - i.e. 5:00pm instead of 5:02pm.

This effect is cumulative, so if a user continues to lock their phone throughout periods of using the app, the timestamps will continue to become more and more incorrect, leading to events that are recorded as happening *hours* before they've actually happened.

### How to reproduce

- Open any app that uses this library to track segment events
- Perform an action on the app that triggers a tracking event.
- Confirm the timestamp on this event is what you expect (E.g. use the debugger tab on segment.com)
- Lock your device for two minutes.
- Unlock your device and perform another action on the app that will trigger a tracking event.
- Observe that your event timestamps are now two minutes too early.

### Our Fix

We've experimented with some changes and produced two options:

- Using the `this.nanosecondTimestamps` boolean to determine whether to generate timestamps using `new NanoDate()`, and to otherwise use a standard `new Date()`. This could be inserted for lines such as [here](https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L586), where `new NanoDate()` is being used. [Proposed fix PR](https://github.com/segmentio/analytics-android/compare/master...oomathias:fix-timestamp-date)
- Employing the use of `System.elapsedRealtimeNanos()` instead of `System.nanoTime()` to count nanoseconds elapsed.  This change, however, would require bumping the `minSdkVersion` from 14 to 17, so would be a major/breaking change. [Proposed fix PR](https://github.com/segmentio/analytics-android/compare/master...oomathias:fix-nanodate)
- Update `analytics-android` and `analytics-react-native`

**Comment by prayansh** [comment]
Hi! @oomathias thank you for the detailed ticket. I have shipped a quick fix (#758) (thank you for your recommended fix) as part of `analytics-android 4.9.3` that should fix this timestamp issue for all users that don't have `experimentalNanosecondTimestamps` flag enabled. 

We are currently working on fixing the nanosecond skew issue, but do not have an ETA for that

**Comment by oomathias** [comment]
@prayansh Thanks for fixing this, could you also bump `segmentio/analytics-react-native` as this is the one we use (I would like to avoid patching the repo).

**Comment by prayansh** [comment]
Hey @oomathias we have a release planned for react-native next week, and I will make sure to include the dependency bump in that release :).

**Comment by prayansh** [comment]
@oomathias sorry for the delay, but we have to bump minimum react-native support of the library to 0.64 because Facebook made some breaking changes and those are causing some issues. We are hoping to have a release by the middle of next week.

**Comment by prayansh** [comment]
@oomathias this fix has been shipped to `analytics-react-native` as of [`v1.4.4`](https://github.com/segmentio/analytics-react-native/releases/tag/v1.4.4). 

Closing this ticket
