### ISSUE TITLE
Crash on initializing Segment

### ISSUE THREAD

**Issue by Pro-55** [segmentio/analytics-android#764]
Segment => `v4.9.3`

Error => 
`Fatal Exception: java.lang.IllegalAccessError: Interface androidx.lifecycle.FullLifecycleObserver implemented by class com.segment.analytics.AnalyticsActivityLifecycleCallbacks is inaccessible (declaration of 'com.segment.analytics.AnalyticsActivityLifecycleCallbacks' appears in base.apk!classes2.dex)
`
Initialization =>
`val analytics = AnalyticsSegment.Builder(context!!, BuildConfig.SegmentKey)
                .experimentalUseNewLifecycleMethods(false)
                .trackApplicationLifecycleEvents() // Enable this to record certain application events automatically!
                .recordScreenViews() // Enable this to record screen views automatically!
                .build()
        AnalyticsSegment.setSingletonInstance(analytics)`

**Comment by Pro-55** [comment]
This only happens in production apk.

I am assuming it is because of proguard optimization

**Comment by prayansh** [comment]
@Pro-55 Does adding this to your proguard file fix the issue?
```
-keep class androidx.lifecycle.**
```

**Comment by prayansh** [comment]
Closing it out. Feel free to reopen if problem persists
