### ISSUE TITLE
Setting `traits` in tracking options cause tracking to fail silently

### ISSUE THREAD

**Issue by stigi** [segmentio/analytics-android#765]
Hi,

I've ran into the issue that traits passed via `options` in `track` are not merged, but override `analyticsContext.traits()`. That happens in the `putAll` here:
https://github.com/segmentio/analytics-android/blob/b089df7808126d22c8f4b9f5850f521cffc65ef9/analytics/src/main/java/com/segment/analytics/Analytics.java#L754-L755

`putAll` does not perform a deep merge, but replaces the entire `traits` key. This causes `anonymousID` to be `null` (unless it is provided via the tracking options again) and causes [`builder.anonymousId(contextCopy.traits().anonymousId());`](https://github.com/segmentio/analytics-android/blob/b089df7808126d22c8f4b9f5850f521cffc65ef9/analytics/src/main/java/com/segment/analytics/Analytics.java#L759) to fail because it [internally asserts against `null` values](https://github.com/segmentio/analytics-android/blob/b089df7808126d22c8f4b9f5850f521cffc65ef9/analytics/src/main/java/com/segment/analytics/integrations/BasePayload.java#L323).

This causes the entire Runnable to fail without an error being visible to the dev.

**Comment by prayansh** [comment]
Hi @stigi, after some careful consideration, the team has decided that we do not want to enable this kind of use-case. Using the `Options` object here is a path that we do not want users to take. I would suggest that if you want to modify traits, you should use an `identify` call to propagate those traits changes.

**Comment by stigi** [comment]
Thanks for clarifying @prayansh. We'll follow your suggestion.

**Comment by Nsquik** [comment]
@prayansh So if you're not wanting to support this use case, is there a way to disable auto collecting the `traits` to context?
🤔 

https://segment.com/docs/connections/spec/common/#context-fields-automatically-collected

**Comment by prayansh** [comment]
@Nsquik you should be able to write a source middleware and strip out the `traits` object as you need.
