### ISSUE TITLE
NullPointer Exception: App crash on launch

### ISSUE THREAD

**Issue by asura1234** [segmentio/analytics-android#766]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'java.util.Set java.util.Map.entrySet()' on a null object reference
```
com.segment.analytics.Analytics.performRun (Analytics.java:1535)
com.segment.analytics.Analytics$10.run (Analytics.java:796)
android.os.Handler.handleCallback (Handler.java:900)
android.os.Handler.dispatchMessage (Handler.java:103)
android.os.Looper.loop (Looper.java:219)
android.app.ActivityThread.main (ActivityThread.java:8349)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)
```

**Comment by asura1234** [comment]
version "com.segment.analytics.android:analytics:4.8.2"

**Comment by prayansh** [comment]
Hmm this may be a timing issue. From what i can tell this is being caused by [`integrations`](https://github.com/segmentio/analytics-android/blob/4.8.2/analytics/src/main/java/com/segment/analytics/Analytics.java#L153) being `null`. Is there a specific scenario where you can consistently reproduce this issue?

**Comment by asura1234** [comment]
> specific scenario where you can consistently reproduce this issue
stilling trying to find it. I saw this exception in firebase. I haven't been able to reproduce it on device.

**Comment by prayansh** [comment]
I see. I too am unable to reproduce the issue, which is why I am thinking its a rare scenario (and a timing issue). I will close the ticket, and feel free to reopen once someone can find a consistent way to reproduce the issue.

**Comment by Y-E-P** [comment]
Case: When you try to shutdown(), executor also called shutdown(), but request in the same moment can be submitted to terminated networkExecutor, thats why, under the hood caused RejectedExecutionException and omit this exception without any handling.
