### ISSUE TITLE
request for Flurry integration plugin for analytics-kotlin

### ISSUE THREAD

**Issue by jom16antonio** [segmentio/analytics-android#788]
Hi 
please do provide a flurry destination class for use in analytics-kotlin. Similar to FirebaseDestination.
Thanks

**Comment by wenxi-zeng** [comment]
hi @jom16antonio we definitely will add more destinations to our kotlin library. would you mind to report this to our [kotlin repo](https://github.com/segmentio/analytics-kotlin), so we can better track the progress there? thanks!
