### ISSUE TITLE
Application lifecycle events are not fired

### ISSUE THREAD

**Issue by teodorpenkov** [segmentio/analytics-android#793]
Hey folks, it seems that application lifecycle events are not fired when we use compose. I'm attaching a simple project that reproduces the issue.

Can you help with that?
[Pet3.zip](https://github.com/segmentio/analytics-android/files/8168686/Pet3.zip)

**Comment by martynamaron** [comment]
Hi @teodorpenkov - has this been resolved? I'm seeing the same in my app (application lifecycle events not firing), although I haven't tried linking it to Compose
