### ISSUE TITLE
Non-Compliant SDK Version

### ISSUE THREAD

**Issue by Svilcata19** [segmentio/analytics-android#802]
Hello, 
Are there any plans to address this? 

<img width="1057" alt="Screenshot 2022-06-10 at 17 38 09" src="https://user-images.githubusercontent.com/33193591/173307325-c801b171-4b45-4dc3-9b8f-5cd9ec555a9f.png">

Thank you in advance!

**Comment by wenxi-zeng** [comment]
as it is stated in the email, this issue is already fixed in `4.10.1` or above.

if you're using segment sdk alone, upgrading to the latest `4.10.4` fixes the issue.
if you're using segment sdk with device mode integration sdks, a fix to the integration sdks is coming this week.
