### ISSUE TITLE
Warning in Google Play Console

### ISSUE THREAD

**Issue by martymiller** [segmentio/analytics-android#803]
Can you confirm that the latest version address this issue?

<img width="654" alt="Screen Shot 2022-06-16 at 1 29 02 AM" src="https://user-images.githubusercontent.com/3698882/174192140-673817b2-ec7f-4733-8138-31b053b22a6e.png">

**Comment by RyanNewsom** [comment]
duplicate, https://github.com/segmentio/analytics-android/issues/802
