### ISSUE TITLE
crash while initialising segment

### ISSUE THREAD

**Issue by shrastiRisor** [segmentio/analytics-android#804]
Crash log: 
com.segment.analytics.internal.Utils.getUniqueID (Utils.java:336)
com.segment.analytics.internal.Utils.getDeviceId (Utils.java:304)
com.segment.analytics.AnalyticsContext.putDevice (AnalyticsContext.java:239)
com.segment.analytics.AnalyticsContext.create (AnalyticsContext.java:134)
com.segment.analytics.Analytics$Builder.build (Analytics.java:1467)
com.risor.core.analytics.AnalyticsManager.initSegment (AnalyticsManager.java:206)

**Comment by wenxi-zeng** [comment]
@shrastiRisor please update to the latest version `4.10.4`
