### ISSUE TITLE
Segment with Intercom

### ISSUE THREAD

**Issue by Lda1984** [segmentio/analytics-android#823]
Hi. We use Segment sdk (4.11.0) it works well, then we integrated Intercom sdk and segment stop sending only lifecycle events, all custom events `.track()` works 

to reproduce, add to build.gradle 
`implementation 'io.intercom.android:intercom-sdk:14.0.4'`

Also, I've found workaround
`.experimentalUseNewLifecycleMethods(false)`
but this feature not documented enough, can it affect something?

**Comment by wenxi-zeng** [comment]
hey @Lda1984, just want to confirm, do you happen to init `analytics` in a background thread?

**Comment by Lda1984** [comment]
> hey @Lda1984, just want to confirm, do you happen to init `analytics` in a background thread?

@wenxi-zeng no, it happens in main thread. is it wrong?

**Comment by wenxi-zeng** [comment]
nope. that's something different than I suspected. we'll have a look. thanks for reporting this issue!

**Comment by Lda1984** [comment]
similar issues https://github.com/segmentio/analytics-android/pull/684

**Comment by wenxi-zeng** [comment]
@Lda1984 sorry take too so long to get you back. this issue should have been resolved by #824 in the latest release 4.11.1. please have a try. if the problem still persists, feel free to reopen the issue and please provide the stack trace so we can better troubleshooting. thanks!
