### ISSUE TITLE
User identify tracking

### ISSUE THREAD

**Issue by sherif95** [segmentio/analytics-android#831]
Hello Dears,

I'm really impressed with your work and thank you for your great efforts.

I have a question about how to check if the user has been tracked before by Segment, Could you please help me?

There was a method called **hasIntegration()** to check if the user has been tracked before or not.

**Comment by wenxi-zeng** [comment]
hey @sherif95, can you be more specific on "check if the user has been tracked before"? do you mean if an user has been identified by the Segment SDK before?

**Comment by sherif95** [comment]
Hey @wenxi-zeng , Yes I mean if a user has been identified by the Segment SDK before

**Comment by wenxi-zeng** [comment]
you should able to check if the userId is set by querying `getAnalyticsContext().traits().currentId()`. if you just started to use this library, it's highly recommended that you switch to our new [analytics-kotlin](https://github.com/segmentio/analytics-kotlin) library. it's way more performant and flexible. you'd only need to do `analytics.userId` to check the same thing in the new library.
