### ISSUE TITLE
App using 4.11.3 rejected by Google because of "Violation of User Data policy"

### ISSUE THREAD

**Issue by nateirwin** [segmentio/analytics-android#840]
We recently submitted a new build to Google for approval, but it was rejected because of a "Violation of User Data Policy":

```
Issue found: Violation of User Data policy
We reviewed SDKs used by your app and found noncompliant version(s) of SDK(s) which collects persistent device identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers.

Issue details

We found an issue in the following area(s):

SPLIT_BUNDLE xxxxxx: :
SDK: Segment com.segment.analytics.android:analytics (consider upgrading to version 4.10.1)
Additionally, follow these steps to bring your app into compliance:

You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK.
```

Google recommends upgrading to version 4.10.1 of the com.segment.analytics.android:analytics package, but we're already on a higher version (4.11.3). I've appealed this with Google, but wondering if anyone else has run into this issue recently?

**Comment by wenxi-zeng** [comment]
hey @nateirwin please refer to the resolution of this [issue](https://github.com/segmentio/analytics-android/issues/820). particularly, follow the instructions in [this comment](https://github.com/segmentio/analytics-android/issues/820#issuecomment-1409311562) to see if it addresses your problem.

**Comment by nateirwin** [comment]
@wenxi-zeng, that resolved the issue. Thank you!
